/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Code.ConnectDB;
import Code.Staff;
import Code.StaffClass;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Chamod
 */
public class AcademicStaff extends javax.swing.JFrame {

    /**
     * Creates new form AcademicStaff
     */
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public AcademicStaff() {
        
        initComponents();
        
        con = ConnectDB.connect();
        
        tableLoadStaff();
        tableLoadStaffClass();
        
    }
    
    public void tableLoadStaff() {
    
        try {
            
            String sql = "SELECT staffId AS 'Staff ID', name AS 'Name', dob AS 'DOB', gender AS 'Gender', civilStatus AS 'Civil Status', nic AS 'NIC', phoneNo AS 'Phone No', address AS 'Address', email AS 'Email', category AS 'Category' FROM staff";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            staffTable.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    
    }
    
    public void tableLoadStaffClass() {
    
        try {
            
            String sql = "SELECT subjectId AS 'Subject ID', instructId AS 'Instructor ID', room AS 'Room' FROM sub_instruct";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            staffClassTable.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LeftPanel = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        backButton1 = new javax.swing.JButton();
        manageStaffBtn = new javax.swing.JButton();
        staffClassBtn = new javax.swing.JButton();
        RightPanel = new javax.swing.JPanel();
        AddNewStaff = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        sCategory = new javax.swing.JTextField();
        sName = new javax.swing.JTextField();
        sEmail = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        sGender = new javax.swing.JTextField();
        sAddress = new javax.swing.JTextField();
        sDob = new javax.swing.JTextField();
        sNic = new javax.swing.JTextField();
        sPhoneNo = new javax.swing.JTextField();
        sStatus = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        staffTable = new javax.swing.JTable();
        sDeleteBtn = new javax.swing.JButton();
        sAddBtn = new javax.swing.JButton();
        sUpdateBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        StaffClass = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        staffClassTable = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        scRoom = new javax.swing.JTextField();
        scSubId = new javax.swing.JTextField();
        scInsId = new javax.swing.JTextField();
        scDeleteBtn = new javax.swing.JButton();
        scAddBtn = new javax.swing.JButton();
        scUpdateBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LeftPanel.setBackground(new java.awt.Color(209, 246, 251));
        LeftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/homeIcon.png"))); // NOI18N
        homeButton.setBorder(null);
        homeButton.setBorderPainted(false);
        homeButton.setContentAreaFilled(false);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        LeftPanel.add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        backButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/backIcon.png"))); // NOI18N
        backButton1.setBorder(null);
        backButton1.setBorderPainted(false);
        backButton1.setContentAreaFilled(false);
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });
        LeftPanel.add(backButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        manageStaffBtn.setText("MANAGE STAFF");
        manageStaffBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageStaffBtnActionPerformed(evt);
            }
        });
        LeftPanel.add(manageStaffBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 120, 50));

        staffClassBtn.setText("STAFF & CLASSROOM");
        staffClassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffClassBtnActionPerformed(evt);
            }
        });
        LeftPanel.add(staffClassBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 150, 50));

        getContentPane().add(LeftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 650));

        RightPanel.setBackground(new java.awt.Color(36, 47, 65));
        RightPanel.setLayout(new java.awt.CardLayout());

        AddNewStaff.setBackground(new java.awt.Color(36, 47, 65));
        AddNewStaff.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(209, 246, 251));
        jLabel8.setText("Manage Staff");
        AddNewStaff.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 400, 30));
        AddNewStaff.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 640, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(209, 246, 251));
        jLabel3.setText("Category");
        AddNewStaff.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 110, 30));

        idLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        idLabel.setForeground(new java.awt.Color(209, 246, 251));
        AddNewStaff.add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 80, 30));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(209, 246, 251));
        jLabel5.setText("Name");
        AddNewStaff.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 80, 30));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(209, 246, 251));
        jLabel6.setText("Date of Birth");
        AddNewStaff.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 110, 30));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(209, 246, 251));
        jLabel9.setText("Civil Status");
        AddNewStaff.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 110, 30));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(209, 246, 251));
        jLabel10.setText("NIC");
        AddNewStaff.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 30, 30));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(209, 246, 251));
        jLabel11.setText("Phone No");
        AddNewStaff.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 110, 30));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(209, 246, 251));
        jLabel12.setText("Address");
        AddNewStaff.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 110, 30));

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(209, 246, 251));
        jLabel13.setText("Email");
        AddNewStaff.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 110, 30));
        AddNewStaff.add(sCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 220, 30));
        AddNewStaff.add(sName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 240, 30));
        AddNewStaff.add(sEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 250, 30));

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(209, 246, 251));
        jLabel14.setText("Gender");
        AddNewStaff.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 50, 30));
        AddNewStaff.add(sGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 40, 30));
        AddNewStaff.add(sAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 200, 30));
        AddNewStaff.add(sDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 200, 30));
        AddNewStaff.add(sNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 140, 30));
        AddNewStaff.add(sPhoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 200, 30));
        AddNewStaff.add(sStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 100, 30));

        staffTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        staffTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staffTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(staffTable);

        AddNewStaff.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 300, 700, 340));

        sDeleteBtn.setText("DELETE");
        sDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sDeleteBtnActionPerformed(evt);
            }
        });
        AddNewStaff.add(sDeleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 100, 40));

        sAddBtn.setText("ADD");
        sAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sAddBtnActionPerformed(evt);
            }
        });
        AddNewStaff.add(sAddBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 100, 40));

        sUpdateBtn.setText("UPDATE");
        sUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sUpdateBtnActionPerformed(evt);
            }
        });
        AddNewStaff.add(sUpdateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 100, 40));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(209, 246, 251));
        jLabel7.setText("Staff ID:");
        AddNewStaff.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 80, 30));

        RightPanel.add(AddNewStaff, "card2");

        StaffClass.setBackground(new java.awt.Color(36, 47, 65));
        StaffClass.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(209, 246, 251));
        jLabel15.setText("Assign Staff & ClassRooms");
        StaffClass.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 400, 30));
        StaffClass.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 640, 10));

        staffClassTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        staffClassTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staffClassTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(staffClassTable);

        StaffClass.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 330, -1));

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(209, 246, 251));
        jLabel16.setText("Room");
        StaffClass.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 80, 30));

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(209, 246, 251));
        jLabel17.setText("Subject ID");
        StaffClass.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 80, 30));

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(209, 246, 251));
        jLabel18.setText("Instructor ID");
        StaffClass.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 110, 30));
        StaffClass.add(scRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 220, 30));
        StaffClass.add(scSubId, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 220, 30));
        StaffClass.add(scInsId, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 220, 30));

        scDeleteBtn.setText("DELETE");
        scDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scDeleteBtnActionPerformed(evt);
            }
        });
        StaffClass.add(scDeleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 100, 40));

        scAddBtn.setText("ADD");
        scAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scAddBtnActionPerformed(evt);
            }
        });
        StaffClass.add(scAddBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 100, 40));

        scUpdateBtn.setText("UPDATE");
        scUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scUpdateBtnActionPerformed(evt);
            }
        });
        StaffClass.add(scUpdateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 100, 40));

        RightPanel.add(StaffClass, "card3");

        getContentPane().add(RightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 730, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed

        Main m = new Main();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed

        Main m = new Main();
        m.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_backButton1ActionPerformed

    private void staffTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffTableMouseClicked
        
        int r = staffTable.getSelectedRow();
        
        String id = staffTable.getValueAt(r, 0).toString();
        String name = staffTable.getValueAt(r, 1).toString();
        String dob = staffTable.getValueAt(r, 2).toString();
        String gender = staffTable.getValueAt(r, 3).toString();
        String status = staffTable.getValueAt(r, 4).toString();
        String nic = staffTable.getValueAt(r, 5).toString();
        String phoneNo = staffTable.getValueAt(r, 6).toString();
        String address = staffTable.getValueAt(r, 7).toString();
        String email = staffTable.getValueAt(r, 8).toString();
        String category = staffTable.getValueAt(r, 9).toString();
        
        idLabel.setText(id);
        sName.setText(name);
        sDob.setText(dob);
        sGender.setText(gender);
        sStatus.setText(status);
        sNic.setText(nic);
        sPhoneNo.setText(phoneNo);
        sAddress.setText(address);
        sEmail.setText(email);
        sCategory.setText(category);
        
    }//GEN-LAST:event_staffTableMouseClicked

    private void sAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sAddBtnActionPerformed
        
        if(sName.getText().isEmpty() || sDob.getText().isEmpty() || sGender.getText().isEmpty() || sStatus.getText().isEmpty() || sNic.getText().isEmpty() || sPhoneNo.getText().isEmpty() || sAddress.getText().isEmpty() || sEmail.getText().isEmpty() || sCategory.getText().isEmpty()) {
            
            JOptionPane.showConfirmDialog(null, "Please Fill All Fields", "Fields are Empty!", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
            
        }
        else {
            
            String name = sName.getText();
            String dob = sDob.getText();
            String gender = sGender.getText();
            String status = sStatus.getText();
            String nic = sNic.getText();
            String phoneNo = sPhoneNo.getText();
            String address = sAddress.getText();
            String email = sEmail.getText();
            String category = sCategory.getText();
            
            Staff s = new Staff(name, dob, gender, status, nic, phoneNo, address, email, category);
            s.add();
            
            sName.setText("");
            sDob.setText("");
            sGender.setText("");
            sStatus.setText("");
            sNic.setText("");
            sPhoneNo.setText("");
            sAddress.setText("");
            sEmail.setText("");
            sCategory.setText("");
            
            tableLoadStaff();
            
        }
        
    }//GEN-LAST:event_sAddBtnActionPerformed

    private void sUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sUpdateBtnActionPerformed
        
        int x = JOptionPane.showConfirmDialog(null, "Do you want to update this record?");
        
        int id = Integer.parseInt(idLabel.getText());
        String name = sName.getText();
        String dob = sDob.getText();
        String gender = sGender.getText();
        String status = sStatus.getText();
        String nic = sNic.getText();
        String phoneNo = sPhoneNo.getText();
        String address = sAddress.getText();
        String email = sEmail.getText();
        String category = sCategory.getText();
        
        if(x==0) {
        
            Staff s = new Staff(id, name, dob, gender, status, nic, phoneNo, address, email, category);
            s.update();
                
            tableLoadStaff();
            
            idLabel.setText("");
            sName.setText("");
            sDob.setText("");
            sGender.setText("");
            sStatus.setText("");
            sNic.setText("");
            sPhoneNo.setText("");
            sAddress.setText("");
            sEmail.setText("");
            sCategory.setText("");
                
        }
        
    }//GEN-LAST:event_sUpdateBtnActionPerformed

    private void sDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sDeleteBtnActionPerformed
        
        int x = JOptionPane.showConfirmDialog(null, "Do you want to delete this record?");
        
        if(x==0) {
        
            int id = Integer.parseInt(idLabel.getText());
            Staff s = new Staff(id);
            s.delete();
                
            tableLoadStaff();

            idLabel.setText("");
            sName.setText("");
            sDob.setText("");
            sGender.setText("");
            sStatus.setText("");
            sNic.setText("");
            sPhoneNo.setText("");
            sAddress.setText("");
            sEmail.setText("");
            sCategory.setText("");
                
        }
        
    }//GEN-LAST:event_sDeleteBtnActionPerformed

    private void staffClassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffClassBtnActionPerformed
        
        RightPanel.removeAll();
        RightPanel.repaint();
        RightPanel.revalidate();

        RightPanel.add(StaffClass);
        RightPanel.repaint();
        RightPanel.revalidate();
        
    }//GEN-LAST:event_staffClassBtnActionPerformed

    private void manageStaffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageStaffBtnActionPerformed
        
        RightPanel.removeAll();
        RightPanel.repaint();
        RightPanel.revalidate();

        RightPanel.add(AddNewStaff);
        RightPanel.repaint();
        RightPanel.revalidate();
        
    }//GEN-LAST:event_manageStaffBtnActionPerformed

    private void staffClassTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffClassTableMouseClicked
        
        int r = staffClassTable.getSelectedRow();
        
        String subId = staffClassTable.getValueAt(r, 0).toString();
        String insId = staffClassTable.getValueAt(r, 1).toString();
        String room = staffClassTable.getValueAt(r, 2).toString();
        
        scSubId.setText(subId);
        scInsId.setText(insId);
        scRoom.setText(room);
        
    }//GEN-LAST:event_staffClassTableMouseClicked

    private void scAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scAddBtnActionPerformed
        
        if(scSubId.getText().isEmpty() || scInsId.getText().isEmpty() || scRoom.getText().isEmpty()) {
            
            JOptionPane.showConfirmDialog(null, "Please Fill All Fields", "Fields are Empty!", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
            
        }
        else {
            
            String subId = scSubId.getText();
            int insId = Integer.parseInt(scInsId.getText());
            String room = scRoom.getText();
            
            StaffClass sc = new StaffClass(subId, insId, room);
            sc.add();
            
            scSubId.setText("");
            scInsId.setText("");
            scRoom.setText("");
            
            tableLoadStaffClass();
            
        }
        
    }//GEN-LAST:event_scAddBtnActionPerformed

    private void scUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scUpdateBtnActionPerformed
        
        int x = JOptionPane.showConfirmDialog(null, "Do you want to update this record?");
        
        String subId = scSubId.getText();
        int insId = Integer.parseInt(scInsId.getText());
        String room = scRoom.getText();
        
        if(x==0) {
        
            StaffClass sc = new StaffClass(subId, insId, room);
            sc.update();
                
            tableLoadStaffClass();

            scSubId.setText("");
            scInsId.setText("");
            scRoom.setText("");
                
        }
        
    }//GEN-LAST:event_scUpdateBtnActionPerformed

    private void scDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scDeleteBtnActionPerformed
        
        int x = JOptionPane.showConfirmDialog(null, "Do you want to delete this record?");
        
        if(x==0) {
        
            String subId = scSubId.getText();
            int insId = Integer.parseInt(scInsId.getText());
            String room = scRoom.getText();
            
            StaffClass sc = new StaffClass(subId, insId, room);
            sc.delete();
                
            tableLoadStaffClass();

            scSubId.setText("");
            scInsId.setText("");
            scRoom.setText("");
                
        }
        
        
    }//GEN-LAST:event_scDeleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcademicStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcademicStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcademicStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcademicStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcademicStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddNewStaff;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JPanel StaffClass;
    private javax.swing.JButton backButton1;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton manageStaffBtn;
    private javax.swing.JButton sAddBtn;
    private javax.swing.JTextField sAddress;
    private javax.swing.JTextField sCategory;
    private javax.swing.JButton sDeleteBtn;
    private javax.swing.JTextField sDob;
    private javax.swing.JTextField sEmail;
    private javax.swing.JTextField sGender;
    private javax.swing.JTextField sName;
    private javax.swing.JTextField sNic;
    private javax.swing.JTextField sPhoneNo;
    private javax.swing.JTextField sStatus;
    private javax.swing.JButton sUpdateBtn;
    private javax.swing.JButton scAddBtn;
    private javax.swing.JButton scDeleteBtn;
    private javax.swing.JTextField scInsId;
    private javax.swing.JTextField scRoom;
    private javax.swing.JTextField scSubId;
    private javax.swing.JButton scUpdateBtn;
    private javax.swing.JButton staffClassBtn;
    private javax.swing.JTable staffClassTable;
    private javax.swing.JTable staffTable;
    // End of variables declaration//GEN-END:variables
}
