/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Code.ConnectDB;
import Code.Course;
import Code.Subject;
import Code.SubjectsLabs;
import Code.SubjectsLecturers;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Chamod
 */
public class CoursesSubjects extends javax.swing.JFrame {

    /**
     * Creates new form CoursesSubjects
     */
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public CoursesSubjects() {
        initComponents();
        
        con = ConnectDB.connect();
        tableLoadCourse();
        tableLoadSubject();
        tableLoadSubLab();
        tableLoadSubLec();
        
    }
    
    public void tableLoadCourse() {
    
        try {
            
            String sql = "SELECT courseId AS 'Course ID', courseName AS 'Course Name', faculty AS 'Faculty', category AS 'Category', duration As 'Duration' FROM course";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            courseTable.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    
    }
    
    public void tableLoadSubject() {
    
        try {
            
            String sql = "SELECT subjectId AS 'Subject ID', name AS 'Subject Name', category AS 'Category', noOfCredits AS 'Number Of Credits', price As 'Price', semId AS 'Semester ID', courseId AS 'Course ID' FROM subject";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            subjectTable.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch (Exception e) {
            
            JOptionPane.showConfirmDialog(null, e);
            
        }
        
    }
    
    public void tableLoadSubLab() {
    
        try {
            
            String sql = "SELECT subjectId AS 'Subject ID', labId AS 'Lab ID', labDuration AS 'Lab Duration' FROM sub_lab";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            subLabTable.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch (Exception e) {
            
            JOptionPane.showConfirmDialog(null, e);
            
        }
    
    }
    
    public void tableLoadSubLec() {
    
        try {
            
            String sql = "SELECT subjectId AS 'Subject ID', lecId AS 'Lecturer ID', room AS 'Lecture Room', duration AS 'Duration' FROM sub_lec";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            subLecTable.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LeftPanel = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        backButton1 = new javax.swing.JButton();
        courseBtn = new javax.swing.JButton();
        subjectsBtn = new javax.swing.JButton();
        subLabBtn = new javax.swing.JButton();
        subLecBtn = new javax.swing.JButton();
        RightPanel = new javax.swing.JPanel();
        Course = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        facultyBox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        categoryBox = new javax.swing.JTextField();
        courseIdBox = new javax.swing.JTextField();
        cNameBox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        durationBox = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        courseTable = new javax.swing.JTable();
        cDeleteBtn = new javax.swing.JButton();
        cAddBtn = new javax.swing.JButton();
        cUpdateBtn = new javax.swing.JButton();
        Subject = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        sPrice = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sSubName = new javax.swing.JTextField();
        sSubId = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        sCategory = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        sSemId = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        sNoOfCredits = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        sCourseId = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        subjectTable = new javax.swing.JTable();
        sDeleteBtn = new javax.swing.JButton();
        sAddBtn = new javax.swing.JButton();
        sUpdateBtn = new javax.swing.JButton();
        SubjectLab = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        subLabTable = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        slDuration = new javax.swing.JTextField();
        slSubId = new javax.swing.JTextField();
        slLabId = new javax.swing.JTextField();
        slDeleteBtn = new javax.swing.JButton();
        slAddBtn = new javax.swing.JButton();
        slUpdateBtn = new javax.swing.JButton();
        SubjectLec = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        subLecTable = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lDuration = new javax.swing.JTextField();
        lSubId = new javax.swing.JTextField();
        lLecId = new javax.swing.JTextField();
        lRoom = new javax.swing.JTextField();
        lDeleteBtn = new javax.swing.JButton();
        lAddBtn = new javax.swing.JButton();
        lUpdateBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LeftPanel.setBackground(new java.awt.Color(209, 246, 251));
        LeftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/homeIcon.png"))); // NOI18N
        homeButton.setBorder(null);
        homeButton.setBorderPainted(false);
        homeButton.setContentAreaFilled(false);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        LeftPanel.add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        backButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/backIcon.png"))); // NOI18N
        backButton1.setBorder(null);
        backButton1.setBorderPainted(false);
        backButton1.setContentAreaFilled(false);
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });
        LeftPanel.add(backButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        courseBtn.setText("COURSES");
        courseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseBtnActionPerformed(evt);
            }
        });
        LeftPanel.add(courseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 180, 50));

        subjectsBtn.setText("SUBJECTS");
        subjectsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectsBtnActionPerformed(evt);
            }
        });
        LeftPanel.add(subjectsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 180, 50));

        subLabBtn.setText("SUBJECTS & LABS");
        subLabBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subLabBtnActionPerformed(evt);
            }
        });
        LeftPanel.add(subLabBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 180, 50));

        subLecBtn.setText("SUBJECTS & LECTURERS");
        subLecBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subLecBtnActionPerformed(evt);
            }
        });
        LeftPanel.add(subLecBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 180, 50));

        getContentPane().add(LeftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 650));

        RightPanel.setBackground(new java.awt.Color(36, 47, 65));
        RightPanel.setLayout(new java.awt.CardLayout());

        Course.setBackground(new java.awt.Color(36, 47, 65));
        Course.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(209, 246, 251));
        jLabel7.setText("Manage Courses");
        Course.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 400, 30));
        Course.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 640, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(209, 246, 251));
        jLabel1.setText("Course Name");
        Course.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, 30));
        Course.add(facultyBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 270, 30));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(209, 246, 251));
        jLabel2.setText("Faculty");
        Course.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 90, 30));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(209, 246, 251));
        jLabel3.setText("Course ID");
        Course.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 80, 30));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(209, 246, 251));
        jLabel4.setText("Category");
        Course.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));
        Course.add(categoryBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 150, 30));
        Course.add(courseIdBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 150, 30));
        Course.add(cNameBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 270, 30));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(209, 246, 251));
        jLabel5.setText("Duration");
        Course.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));
        Course.add(durationBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 150, 30));

        courseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        courseTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                courseTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(courseTable);

        Course.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 650, 340));

        cDeleteBtn.setText("DELETE");
        cDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cDeleteBtnActionPerformed(evt);
            }
        });
        Course.add(cDeleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 110, 40));

        cAddBtn.setText("ADD");
        cAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cAddBtnActionPerformed(evt);
            }
        });
        Course.add(cAddBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 110, 40));

        cUpdateBtn.setText("UPDATE");
        cUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cUpdateBtnActionPerformed(evt);
            }
        });
        Course.add(cUpdateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 110, 40));

        RightPanel.add(Course, "card2");

        Subject.setBackground(new java.awt.Color(36, 47, 65));
        Subject.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(209, 246, 251));
        jLabel8.setText("Manage Subjects");
        Subject.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 400, 30));
        Subject.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 640, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(209, 246, 251));
        jLabel6.setText("Category");
        Subject.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 70, 30));
        Subject.add(sPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 120, 30));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(209, 246, 251));
        jLabel9.setText("Subject ID");
        Subject.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 57, 70, 30));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(209, 246, 251));
        jLabel10.setText("Course ID");
        Subject.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, 30));
        Subject.add(sSubName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 320, 30));
        Subject.add(sSubId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 70, 30));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(209, 246, 251));
        jLabel11.setText("Subject Name");
        Subject.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 57, -1, 30));
        Subject.add(sCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 70, 30));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(209, 246, 251));
        jLabel12.setText("No Of Credits");
        Subject.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, 30));
        Subject.add(sSemId, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 80, 30));

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(209, 246, 251));
        jLabel13.setText("Price");
        Subject.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 50, 30));
        Subject.add(sNoOfCredits, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 80, 30));

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(209, 246, 251));
        jLabel14.setText("Semester ID");
        Subject.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, 30));
        Subject.add(sCourseId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 70, 30));

        subjectTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        subjectTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subjectTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(subjectTable);

        Subject.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 270, 680, 350));

        sDeleteBtn.setText("DELETE");
        sDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sDeleteBtnActionPerformed(evt);
            }
        });
        Subject.add(sDeleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 110, 40));

        sAddBtn.setText("ADD");
        sAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sAddBtnActionPerformed(evt);
            }
        });
        Subject.add(sAddBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 110, 40));

        sUpdateBtn.setText("UPDATE");
        sUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sUpdateBtnActionPerformed(evt);
            }
        });
        Subject.add(sUpdateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 110, 40));

        RightPanel.add(Subject, "card3");

        SubjectLab.setBackground(new java.awt.Color(36, 47, 65));
        SubjectLab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(209, 246, 251));
        jLabel15.setText("Manage Subjects & Labs");
        SubjectLab.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 400, 30));
        SubjectLab.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 640, -1));

        subLabTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        subLabTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subLabTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(subLabTable);

        SubjectLab.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 320, -1));

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(209, 246, 251));
        jLabel16.setText("Lab Duration");
        SubjectLab.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, -1, -1));

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(209, 246, 251));
        jLabel17.setText("Subject ID");
        SubjectLab.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(209, 246, 251));
        jLabel18.setText("Lab ID");
        SubjectLab.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, -1, -1));
        SubjectLab.add(slDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 230, 30));
        SubjectLab.add(slSubId, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 230, 30));
        SubjectLab.add(slLabId, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 230, 30));

        slDeleteBtn.setText("DELETE");
        slDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slDeleteBtnActionPerformed(evt);
            }
        });
        SubjectLab.add(slDeleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 110, 40));

        slAddBtn.setText("ADD");
        slAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slAddBtnActionPerformed(evt);
            }
        });
        SubjectLab.add(slAddBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 110, 40));

        slUpdateBtn.setText("UPDATE");
        slUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slUpdateBtnActionPerformed(evt);
            }
        });
        SubjectLab.add(slUpdateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 110, 40));

        RightPanel.add(SubjectLab, "card4");

        SubjectLec.setBackground(new java.awt.Color(36, 47, 65));
        SubjectLec.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(209, 246, 251));
        jLabel19.setText("Subjects & Lecturers");
        SubjectLec.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 400, 30));
        SubjectLec.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 640, -1));

        subLecTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        subLecTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subLecTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(subLecTable);

        SubjectLec.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 300, 430));

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(209, 246, 251));
        jLabel20.setText("Duration");
        SubjectLec.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 90, 30));

        jLabel21.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(209, 246, 251));
        jLabel21.setText("Subject ID");
        SubjectLec.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 90, 30));

        jLabel22.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(209, 246, 251));
        jLabel22.setText("Lecturer ID");
        SubjectLec.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 90, 30));

        jLabel23.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(209, 246, 251));
        jLabel23.setText("Lecture Room");
        SubjectLec.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 120, 30));
        SubjectLec.add(lDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 210, 30));
        SubjectLec.add(lSubId, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 210, 30));
        SubjectLec.add(lLecId, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 210, 30));
        SubjectLec.add(lRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 210, 30));

        lDeleteBtn.setText("DELETE");
        lDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lDeleteBtnActionPerformed(evt);
            }
        });
        SubjectLec.add(lDeleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 100, 40));

        lAddBtn.setText("ADD");
        lAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lAddBtnActionPerformed(evt);
            }
        });
        SubjectLec.add(lAddBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 100, 40));

        lUpdateBtn.setText("UPDATE");
        lUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lUpdateBtnActionPerformed(evt);
            }
        });
        SubjectLec.add(lUpdateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, 100, 40));

        RightPanel.add(SubjectLec, "card5");

        getContentPane().add(RightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 730, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed

        Main m = new Main();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed

        Main m = new Main();
        m.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_backButton1ActionPerformed

    private void courseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseBtnActionPerformed
        
        RightPanel.removeAll();
        RightPanel.repaint();
        RightPanel.revalidate();

        RightPanel.add(Course);
        RightPanel.repaint();
        RightPanel.revalidate();
        
    }//GEN-LAST:event_courseBtnActionPerformed

    private void courseTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courseTableMouseClicked
        
        int r = courseTable.getSelectedRow();
        
        String courseId = courseTable.getValueAt(r, 0).toString();
        String courseName = courseTable.getValueAt(r, 1).toString();
        String faculty = courseTable.getValueAt(r, 2).toString();
        String category = courseTable.getValueAt(r, 3).toString();
        String duration = courseTable.getValueAt(r, 4).toString();
        
        courseIdBox.setText(courseId);
        cNameBox.setText(courseName);
        facultyBox.setText(faculty);
        categoryBox.setText(category);
        durationBox.setText(duration);
        
    }//GEN-LAST:event_courseTableMouseClicked

    private void cAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cAddBtnActionPerformed
        
        if(courseIdBox.getText().isEmpty() || cNameBox.getText().isEmpty() || facultyBox.getText().isEmpty() || categoryBox.getText().isEmpty() || durationBox.getText().isEmpty()) {
            
            JOptionPane.showConfirmDialog(null, "Please Fill All Fields", "Fields are Empty!", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
            
        }
        else {
            
            String courseId = courseIdBox.getText();
            String courseName = cNameBox.getText();
            String faculty = facultyBox.getText();
            String category = categoryBox.getText();
            int duration = Integer.parseInt(durationBox.getText());
            
            Course c = new Course(courseId, courseName, faculty, category, duration);
            c.add();
            
            courseIdBox.setText("");
            cNameBox.setText("");
            facultyBox.setText("");
            categoryBox.setText("");
            durationBox.setText("");
            
            tableLoadCourse();
            
        }
        
    }//GEN-LAST:event_cAddBtnActionPerformed

    private void cUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cUpdateBtnActionPerformed
        
        int x = JOptionPane.showConfirmDialog(null, "Do you want to update this record?");
        
        String courseId = courseIdBox.getText();
        String courseName = cNameBox.getText();
        String faculty = facultyBox.getText();
        String category = categoryBox.getText();
        int duration = Integer.parseInt(durationBox.getText());
        
        if(x==0) {
        
            Course c = new Course(courseId, courseName, faculty, category, duration);
            c.update();
                
            tableLoadCourse();

            courseIdBox.setText("");
            cNameBox.setText("");
            facultyBox.setText("");
            categoryBox.setText("");
            durationBox.setText("");
                
        }
        
    }//GEN-LAST:event_cUpdateBtnActionPerformed

    private void cDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cDeleteBtnActionPerformed
        
        int x = JOptionPane.showConfirmDialog(null, "Do you want to delete this record?");
        
        if(x==0) {
        
            String courseId = courseIdBox.getText();
            Course c = new Course(courseId);
            c.delete();
                
            tableLoadCourse();

            courseIdBox.setText("");
            cNameBox.setText("");
            facultyBox.setText("");
            categoryBox.setText("");
            durationBox.setText("");
                
        }
        
    }//GEN-LAST:event_cDeleteBtnActionPerformed

    private void subjectsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectsBtnActionPerformed
        
        RightPanel.removeAll();
        RightPanel.repaint();
        RightPanel.revalidate();

        RightPanel.add(Subject);
        RightPanel.repaint();
        RightPanel.revalidate();
        
    }//GEN-LAST:event_subjectsBtnActionPerformed

    private void subjectTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subjectTableMouseClicked
        
        int r = subjectTable.getSelectedRow();
        
        String subjectId = subjectTable.getValueAt(r, 0).toString();
        String subjectName = subjectTable.getValueAt(r, 1).toString();
        String category = subjectTable.getValueAt(r, 2).toString();
        String noOfCredits = subjectTable.getValueAt(r, 3).toString();
        String price = subjectTable.getValueAt(r, 4).toString();
        String semId = subjectTable.getValueAt(r, 5).toString();
        String courseId = subjectTable.getValueAt(r, 6).toString();
        
        sSubId.setText(subjectId);
        sSubName.setText(subjectName);
        sCategory.setText(category);
        sNoOfCredits.setText(noOfCredits);
        sPrice.setText(price);
        sSemId.setText(semId);
        sCourseId.setText(courseId);
        
    }//GEN-LAST:event_subjectTableMouseClicked

    private void sAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sAddBtnActionPerformed
        
        if(sSubId.getText().isEmpty() || sSubName.getText().isEmpty() || sCategory.getText().isEmpty() || sNoOfCredits.getText().isEmpty() || sPrice.getText().isEmpty() || sSemId.getText().isEmpty() || sCourseId.getText().isEmpty()) {
            
            JOptionPane.showConfirmDialog(null, "Please Fill All Fields", "Fields are Empty!", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
            
        }
        else {
            
            String subId = sSubId.getText();
            String subName = sSubName.getText();
            String category = sCategory.getText();
            int noOfCredits = Integer.parseInt(sNoOfCredits.getText());
            double price = Double.parseDouble(sPrice.getText());
            String semId = sSemId.getText();
            String courseId = sCourseId.getText();
            
            Subject s = new Subject(subId, subName, category, noOfCredits, price, semId, courseId);
            s.add();
            
            sSubId.setText("");
            sSubName.setText("");
            sCategory.setText("");
            sNoOfCredits.setText("");
            sPrice.setText("");
            sSemId.setText("");
            sCourseId.setText("");
            
            tableLoadSubject();
            
        }
        
    }//GEN-LAST:event_sAddBtnActionPerformed

    private void sUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sUpdateBtnActionPerformed
        
        int x = JOptionPane.showConfirmDialog(null, "Do you want to update this record?");
        
        String subId = sSubId.getText();
        String subName = sSubName.getText();
        String category = sCategory.getText();
        int noOfCredits = Integer.parseInt(sNoOfCredits.getText());
        double price = Double.parseDouble(sPrice.getText());
        String semId = sSemId.getText();
        String courseId = sCourseId.getText();
        
        if(x==0) {
        
            Subject s = new Subject(subId, subName, category, noOfCredits, price, semId, courseId);
            s.update();
                
            tableLoadSubject();

            sSubId.setText("");
            sSubName.setText("");
            sCategory.setText("");
            sNoOfCredits.setText("");
            sPrice.setText("");
            sSemId.setText("");
            sCourseId.setText("");
                
        }
        
    }//GEN-LAST:event_sUpdateBtnActionPerformed

    private void sDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sDeleteBtnActionPerformed
        
        int x = JOptionPane.showConfirmDialog(null, "Do you want to delete this record?");
        
        if(x==0) {
        
            String subId = sSubId.getText();
            Subject s = new Subject(subId);
            s.delete();
                
            tableLoadSubject();

            sSubId.setText("");
            sSubName.setText("");
            sCategory.setText("");
            sNoOfCredits.setText("");
            sPrice.setText("");
            sSemId.setText("");
            sCourseId.setText("");
                
        }
        
    }//GEN-LAST:event_sDeleteBtnActionPerformed

    private void subLabBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subLabBtnActionPerformed
        
        RightPanel.removeAll();
        RightPanel.repaint();
        RightPanel.revalidate();

        RightPanel.add(SubjectLab);
        RightPanel.repaint();
        RightPanel.revalidate();
        
    }//GEN-LAST:event_subLabBtnActionPerformed

    private void subLabTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subLabTableMouseClicked
        
        int r = subLabTable.getSelectedRow();
        
        String subId = subLabTable.getValueAt(r, 0).toString();
        String labId = subLabTable.getValueAt(r, 1).toString();
        String duration = subLabTable.getValueAt(r, 2).toString();
        
        slSubId.setText(subId);
        slLabId.setText(labId);
        slDuration.setText(duration);
        
        
    }//GEN-LAST:event_subLabTableMouseClicked

    private void slAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slAddBtnActionPerformed
        
        if(slSubId.getText().isEmpty() || slLabId.getText().isEmpty() || slDuration.getText().isEmpty()) {
            
            JOptionPane.showConfirmDialog(null, "Please Fill All Fields", "Fields are Empty!", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
            
        }
        else {
            
            String subId = slSubId.getText();
            String labId = slLabId.getText();
            int duration = Integer.parseInt(slDuration.getText());
            
            SubjectsLabs sl = new SubjectsLabs(subId, labId, duration);
            sl.add();
            
            slSubId.setText("");
            slLabId.setText("");
            slDuration.setText("");
            
            tableLoadSubLab();
            
        }
        
    }//GEN-LAST:event_slAddBtnActionPerformed

    private void slUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slUpdateBtnActionPerformed
        
        int x = JOptionPane.showConfirmDialog(null, "Do you want to update this record?");
        
        String subId = slSubId.getText();
        String labId = slLabId.getText();
        int duration = Integer.parseInt(slDuration.getText());
        
        if(x==0) {
        
            SubjectsLabs sl = new SubjectsLabs(subId, labId, duration);
            sl.update();
            
            slSubId.setText("");
            slLabId.setText("");
            slDuration.setText("");
            
            tableLoadSubLab();
                
        }
        
    }//GEN-LAST:event_slUpdateBtnActionPerformed

    private void slDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slDeleteBtnActionPerformed
        
        int x = JOptionPane.showConfirmDialog(null, "Do you want to delete this record?");
        
        if(x==0) {
        
            String subId = slSubId.getText();
            String labId = slLabId.getText();
            int duration = Integer.parseInt(slDuration.getText());
            
            SubjectsLabs sl = new SubjectsLabs(subId, labId, duration);
            sl.delete();
                
            tableLoadSubLab();

            slSubId.setText("");
            slLabId.setText("");
            slDuration.setText("");
                
        }
        
        
    }//GEN-LAST:event_slDeleteBtnActionPerformed

    private void subLecBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subLecBtnActionPerformed
        
        RightPanel.removeAll();
        RightPanel.repaint();
        RightPanel.revalidate();

        RightPanel.add(SubjectLec);
        RightPanel.repaint();
        RightPanel.revalidate();
        
    }//GEN-LAST:event_subLecBtnActionPerformed

    private void subLecTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subLecTableMouseClicked
        
        int r = subLecTable.getSelectedRow();
        
        String subId = subLecTable.getValueAt(r, 0).toString();
        String lecId = subLecTable.getValueAt(r, 1).toString();
        String room = subLecTable.getValueAt(r, 2).toString();
        String duration = subLecTable.getValueAt(r, 3).toString();
        
        lSubId.setText(subId);
        lLecId.setText(lecId);
        lRoom.setText(room);
        lDuration.setText(duration);
        
    }//GEN-LAST:event_subLecTableMouseClicked

    private void lAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lAddBtnActionPerformed
        
        if(lSubId.getText().isEmpty() || lLecId.getText().isEmpty() || lRoom.getText().isEmpty() || lDuration.getText().isEmpty()) {
            
            JOptionPane.showConfirmDialog(null, "Please Fill All Fields", "Fields are Empty!", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
            
        }
        else {
            
            String subId = lSubId.getText();
            int lecId = Integer.parseInt(lLecId.getText());
            String room = lRoom.getText();
            int duration = Integer.parseInt(lDuration.getText());
            
            SubjectsLecturers sl = new SubjectsLecturers(subId, lecId, room, duration);
            sl.add();
            
            lSubId.setText("");
            lLecId.setText("");
            lRoom.setText("");
            lDuration.setText("");
            
            tableLoadSubLec();
            
        }
        
    }//GEN-LAST:event_lAddBtnActionPerformed

    private void lUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lUpdateBtnActionPerformed
        
        int x = JOptionPane.showConfirmDialog(null, "Do you want to update this record?");
        
        String subId = lSubId.getText();
        int lecId = Integer.parseInt(lLecId.getText());
        String room = lRoom.getText();
        int duration = Integer.parseInt(lDuration.getText());
        
        if(x==0) {
        
            SubjectsLecturers sl = new SubjectsLecturers(subId, lecId, room, duration);
            sl.update();
            
            lSubId.setText("");
            lLecId.setText("");
            lRoom.setText("");
            lDuration.setText("");
            
            tableLoadSubLec();
                
        }
        
    }//GEN-LAST:event_lUpdateBtnActionPerformed

    private void lDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lDeleteBtnActionPerformed
        
        int x = JOptionPane.showConfirmDialog(null, "Do you want to delete this record?");
        
        if(x==0) {
        
            String subId = lSubId.getText();
            int lecId = Integer.parseInt(lLecId.getText());
            String room = lRoom.getText();
            int duration = Integer.parseInt(lDuration.getText());
            
            SubjectsLecturers sl = new SubjectsLecturers(subId, lecId, room, duration);
            sl.delete();
            
            lSubId.setText("");
            lLecId.setText("");
            lRoom.setText("");
            lDuration.setText("");
            
            tableLoadSubLec();
                
        }
        
    }//GEN-LAST:event_lDeleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoursesSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoursesSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoursesSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoursesSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoursesSubjects().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Course;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JPanel Subject;
    private javax.swing.JPanel SubjectLab;
    private javax.swing.JPanel SubjectLec;
    private javax.swing.JButton backButton1;
    private javax.swing.JButton cAddBtn;
    private javax.swing.JButton cDeleteBtn;
    private javax.swing.JTextField cNameBox;
    private javax.swing.JButton cUpdateBtn;
    private javax.swing.JTextField categoryBox;
    private javax.swing.JButton courseBtn;
    private javax.swing.JTextField courseIdBox;
    private javax.swing.JTable courseTable;
    private javax.swing.JTextField durationBox;
    private javax.swing.JTextField facultyBox;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton lAddBtn;
    private javax.swing.JButton lDeleteBtn;
    private javax.swing.JTextField lDuration;
    private javax.swing.JTextField lLecId;
    private javax.swing.JTextField lRoom;
    private javax.swing.JTextField lSubId;
    private javax.swing.JButton lUpdateBtn;
    private javax.swing.JButton sAddBtn;
    private javax.swing.JTextField sCategory;
    private javax.swing.JTextField sCourseId;
    private javax.swing.JButton sDeleteBtn;
    private javax.swing.JTextField sNoOfCredits;
    private javax.swing.JTextField sPrice;
    private javax.swing.JTextField sSemId;
    private javax.swing.JTextField sSubId;
    private javax.swing.JTextField sSubName;
    private javax.swing.JButton sUpdateBtn;
    private javax.swing.JButton slAddBtn;
    private javax.swing.JButton slDeleteBtn;
    private javax.swing.JTextField slDuration;
    private javax.swing.JTextField slLabId;
    private javax.swing.JTextField slSubId;
    private javax.swing.JButton slUpdateBtn;
    private javax.swing.JButton subLabBtn;
    private javax.swing.JTable subLabTable;
    private javax.swing.JButton subLecBtn;
    private javax.swing.JTable subLecTable;
    private javax.swing.JTable subjectTable;
    private javax.swing.JButton subjectsBtn;
    // End of variables declaration//GEN-END:variables
}
