/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Code.ConnectDB;
import Code.Lab;
import Code.LabInstruct;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Chamod
 */
public class LabAndClassroom extends javax.swing.JFrame {

    /**
     * Creates new form AcademicStaff
     */
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public LabAndClassroom() {
        initComponents();
        
        con = ConnectDB.connect();
        tableLoadLab();
        tableLoadLA();
        
    }
    
    //importing Lab table from database
    public void tableLoadLab(){
        
        try {
            
            String sql = "SELECT labId AS 'Lab ID', name AS 'Lab Name', capacity AS 'Lab Capacity' FROM lab";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            labTable.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
        
    }
    
    //importing lab_instruct table from database
    public void tableLoadLA(){
        
        try {
            
            String sql = "SELECT labId AS 'Lab ID', instructId AS 'Instructor ID' FROM lab_instruct";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            assignLabTable.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LeftPanel = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        backButton1 = new javax.swing.JButton();
        manageLabButton = new javax.swing.JButton();
        assignLabsBtn = new javax.swing.JButton();
        RightPanel = new javax.swing.JPanel();
        ManageLabs = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        labTable = new javax.swing.JTable();
        labCapacityBox = new javax.swing.JTextField();
        labIdBox = new javax.swing.JTextField();
        labNameBox = new javax.swing.JTextField();
        updateLabButton = new javax.swing.JButton();
        deleteLabButton = new javax.swing.JButton();
        addLabButton = new javax.swing.JButton();
        AssignLabs = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        assignLabTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        alInsIdBox = new javax.swing.JTextField();
        alLabIdBox = new javax.swing.JTextField();
        alDeleteBtn = new javax.swing.JButton();
        alAddbtn = new javax.swing.JButton();
        alUpdateBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LeftPanel.setBackground(new java.awt.Color(209, 246, 251));
        LeftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/homeIcon.png"))); // NOI18N
        homeButton.setBorder(null);
        homeButton.setBorderPainted(false);
        homeButton.setContentAreaFilled(false);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        LeftPanel.add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        backButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/backIcon.png"))); // NOI18N
        backButton1.setBorder(null);
        backButton1.setBorderPainted(false);
        backButton1.setContentAreaFilled(false);
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });
        LeftPanel.add(backButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        manageLabButton.setText("MANAGE LABS");
        manageLabButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageLabButtonActionPerformed(evt);
            }
        });
        LeftPanel.add(manageLabButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 110, 50));

        assignLabsBtn.setText("ASSIGN LABS");
        assignLabsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignLabsBtnActionPerformed(evt);
            }
        });
        LeftPanel.add(assignLabsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 110, 50));

        getContentPane().add(LeftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 650));

        RightPanel.setBackground(new java.awt.Color(36, 47, 65));
        RightPanel.setLayout(new java.awt.CardLayout());

        ManageLabs.setBackground(new java.awt.Color(36, 47, 65));
        ManageLabs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(209, 246, 251));
        jLabel7.setText("Add & Manage Labs");
        ManageLabs.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 220, 40));
        ManageLabs.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 640, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(209, 246, 251));
        jLabel1.setText("Capacity");
        ManageLabs.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 90, 20));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(209, 246, 251));
        jLabel2.setText("Lab Name");
        ManageLabs.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 90, 20));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(209, 246, 251));
        jLabel3.setText("Lab ID");
        ManageLabs.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 90, 20));

        labTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        labTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(labTable);

        ManageLabs.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 370, 370));
        ManageLabs.add(labCapacityBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 210, 30));
        ManageLabs.add(labIdBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 210, 30));
        ManageLabs.add(labNameBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 210, 30));

        updateLabButton.setText("UPDATE");
        updateLabButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateLabButtonActionPerformed(evt);
            }
        });
        ManageLabs.add(updateLabButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 140, 40));

        deleteLabButton.setText("DELETE");
        deleteLabButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteLabButtonActionPerformed(evt);
            }
        });
        ManageLabs.add(deleteLabButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, 140, 40));

        addLabButton.setText("ADD");
        addLabButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLabButtonActionPerformed(evt);
            }
        });
        ManageLabs.add(addLabButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 140, 40));

        RightPanel.add(ManageLabs, "card2");

        AssignLabs.setBackground(new java.awt.Color(36, 47, 65));
        AssignLabs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(209, 246, 251));
        jLabel8.setText("Assigning Labs");
        AssignLabs.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 220, 40));
        AssignLabs.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 640, -1));

        assignLabTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        assignLabTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                assignLabTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(assignLabTable);

        AssignLabs.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 280, 360));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(209, 246, 251));
        jLabel4.setText("Instructor ID");
        AssignLabs.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, 30));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(209, 246, 251));
        jLabel5.setText("Lab ID");
        AssignLabs.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 70, 20));
        AssignLabs.add(alInsIdBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 180, 30));
        AssignLabs.add(alLabIdBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 180, 30));

        alDeleteBtn.setText("DELETE");
        alDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alDeleteBtnActionPerformed(evt);
            }
        });
        AssignLabs.add(alDeleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 120, 40));

        alAddbtn.setText("ADD");
        alAddbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alAddbtnActionPerformed(evt);
            }
        });
        AssignLabs.add(alAddbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 120, 40));

        alUpdateBtn.setText("UPDATE");
        alUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alUpdateBtnActionPerformed(evt);
            }
        });
        AssignLabs.add(alUpdateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 120, 40));

        RightPanel.add(AssignLabs, "card3");

        getContentPane().add(RightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 730, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed

        Main m = new Main();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed

        Main m = new Main();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButton1ActionPerformed

    private void manageLabButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageLabButtonActionPerformed
        
        RightPanel.removeAll();
        RightPanel.repaint();
        RightPanel.revalidate();

        RightPanel.add(ManageLabs);
        RightPanel.repaint();
        RightPanel.revalidate();
        
    }//GEN-LAST:event_manageLabButtonActionPerformed

    private void updateLabButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateLabButtonActionPerformed
        
        int x = JOptionPane.showConfirmDialog(null, "Do you want to update this record?");
        
        String labId = labIdBox.getText();
        String labName = labNameBox.getText();
        int capacity = Integer.parseInt(labCapacityBox.getText());
        
        if(x==0) {
        
            Lab l = new Lab(labId, labName, capacity);
            l.updateLab();
       
            tableLoadLab();
                
            labIdBox.setText("");
            labNameBox.setText("");
            labCapacityBox.setText("");
                
        }
        
    }//GEN-LAST:event_updateLabButtonActionPerformed

    private void addLabButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLabButtonActionPerformed
        
        if(labIdBox.getText().isEmpty() || labNameBox.getText().isEmpty() || labCapacityBox.getText().isEmpty()) {
            JOptionPane.showConfirmDialog(null, "Please Fill All Fields", "Fields are Empty!", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            
            String labId = labIdBox.getText();
            String labName = labNameBox.getText();
            int capacity = Integer.parseInt(labCapacityBox.getText());
            
            Lab l = new Lab(labId, labName, capacity);
            
            l.addLab();
            
            labIdBox.setText("");
            labNameBox.setText("");
            labCapacityBox.setText("");
            tableLoadLab();
            
        }
        
    }//GEN-LAST:event_addLabButtonActionPerformed

    private void labTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labTableMouseClicked
        
        int r = labTable.getSelectedRow();
        
        String labId = labTable.getValueAt(r, 0).toString();
        String labName = labTable.getValueAt(r, 1).toString();
        String capacity = labTable.getValueAt(r, 2).toString();
        
        labIdBox.setText(labId);
        labNameBox.setText(labName);
        labCapacityBox.setText(capacity);
        
    }//GEN-LAST:event_labTableMouseClicked

    private void deleteLabButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteLabButtonActionPerformed
        
        int x = JOptionPane.showConfirmDialog(null, "Do you want to delete this record?");
        
        if(x==0) {
        
            String labId = labIdBox.getText();
            
            Lab l = new Lab(labId);
            l.deleteLab();
            
            
            tableLoadLab();
                
            labIdBox.setText("");
            labNameBox.setText("");
            labCapacityBox.setText("");
                
            
        }
        
    }//GEN-LAST:event_deleteLabButtonActionPerformed

    private void assignLabsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignLabsBtnActionPerformed
        
        RightPanel.removeAll();
        RightPanel.repaint();
        RightPanel.revalidate();

        RightPanel.add(AssignLabs);
        RightPanel.repaint();
        RightPanel.revalidate();
        
    }//GEN-LAST:event_assignLabsBtnActionPerformed

    private void assignLabTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assignLabTableMouseClicked
        
        int r = assignLabTable.getSelectedRow();
        
        String labId = assignLabTable.getValueAt(r, 0).toString();
        String instructId = assignLabTable.getValueAt(r, 1).toString();
        
        alLabIdBox.setText(labId);
        alInsIdBox.setText(instructId);
        
    }//GEN-LAST:event_assignLabTableMouseClicked

    private void alAddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alAddbtnActionPerformed
        
        if(alLabIdBox.getText().isEmpty() || alInsIdBox.getText().isEmpty()) {
            JOptionPane.showConfirmDialog(null, "Please Fill All Fields", "Fields are Empty!", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            
            String labId = alLabIdBox.getText();
            String insId = alInsIdBox.getText();
            
            LabInstruct li = new LabInstruct(labId, insId);
            li.addAssign();
            
            alLabIdBox.setText("");
            alInsIdBox.setText("");
            tableLoadLA();
        
        }
        
    }//GEN-LAST:event_alAddbtnActionPerformed

    private void alUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alUpdateBtnActionPerformed
        
        int x = JOptionPane.showConfirmDialog(null, "Do you want to update this record?");
        
        String labId = alLabIdBox.getText();
        String insId = alInsIdBox.getText();
        
        if(x==0) {
        
            LabInstruct li = new LabInstruct(labId, insId);
            li.updateAssign();
                
            tableLoadLA();

            alLabIdBox.setText("");
            alInsIdBox.setText("");
                
        } 
        
    }//GEN-LAST:event_alUpdateBtnActionPerformed

    private void alDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alDeleteBtnActionPerformed
        
        int x = JOptionPane.showConfirmDialog(null, "Do you want to delete this record?");
        
        if(x==0) {
        
            String labId = alLabIdBox.getText();
            String insId = alInsIdBox.getText();
            
            LabInstruct li = new LabInstruct(labId, insId);
            li.deleteAssign();
            
            tableLoadLA();

            alLabIdBox.setText("");
            alInsIdBox.setText("");
            
        }
        
    }//GEN-LAST:event_alDeleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LabAndClassroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LabAndClassroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LabAndClassroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LabAndClassroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LabAndClassroom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AssignLabs;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JPanel ManageLabs;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JButton addLabButton;
    private javax.swing.JButton alAddbtn;
    private javax.swing.JButton alDeleteBtn;
    private javax.swing.JTextField alInsIdBox;
    private javax.swing.JTextField alLabIdBox;
    private javax.swing.JButton alUpdateBtn;
    private javax.swing.JTable assignLabTable;
    private javax.swing.JButton assignLabsBtn;
    private javax.swing.JButton backButton1;
    private javax.swing.JButton deleteLabButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField labCapacityBox;
    private javax.swing.JTextField labIdBox;
    private javax.swing.JTextField labNameBox;
    private javax.swing.JTable labTable;
    private javax.swing.JButton manageLabButton;
    private javax.swing.JButton updateLabButton;
    // End of variables declaration//GEN-END:variables
}
