/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Code.ConnectDB;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Chamod
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public Login() {
        initComponents();
        con = ConnectDB.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NSBM = new javax.swing.JLabel();
        GreenUniveristy = new javax.swing.JLabel();
        nsbmLogo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        usernameBox = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordBox = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        userLogo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NSBM Green University");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(97, 212, 195));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NSBM.setFont(new java.awt.Font("Trajan Pro", 1, 48)); // NOI18N
        NSBM.setForeground(new java.awt.Color(36, 47, 65));
        NSBM.setText("NSBM");
        jPanel1.add(NSBM, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 190, 90));

        GreenUniveristy.setFont(new java.awt.Font("Trajan Pro", 1, 28)); // NOI18N
        GreenUniveristy.setForeground(new java.awt.Color(36, 47, 65));
        GreenUniveristy.setText("GREEN UNIVERSITY");
        jPanel1.add(GreenUniveristy, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 320, 60));

        nsbmLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/NSBM logo.png"))); // NOI18N
        jPanel1.add(nsbmLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 210, 240));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 650));

        jPanel2.setBackground(new java.awt.Color(36, 47, 65));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameLabel.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(97, 212, 195));
        usernameLabel.setText("Username");
        jPanel2.add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, 20));

        usernameBox.setBackground(new java.awt.Color(36, 47, 65));
        usernameBox.setFont(new java.awt.Font("Adobe Arabic", 0, 22)); // NOI18N
        usernameBox.setForeground(new java.awt.Color(97, 212, 195));
        usernameBox.setBorder(null);
        jPanel2.add(usernameBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 280, 30));

        passwordLabel.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(97, 212, 195));
        passwordLabel.setText("Password");
        jPanel2.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, 30));

        passwordBox.setBackground(new java.awt.Color(36, 47, 65));
        passwordBox.setFont(new java.awt.Font("Adobe Arabic", 0, 22)); // NOI18N
        passwordBox.setForeground(new java.awt.Color(97, 212, 195));
        passwordBox.setBorder(null);
        jPanel2.add(passwordBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 280, 20));

        loginButton.setBackground(new java.awt.Color(36, 47, 65));
        loginButton.setFont(new java.awt.Font("Trajan Pro", 1, 15)); // NOI18N
        loginButton.setForeground(new java.awt.Color(97, 212, 195));
        loginButton.setText("Login");
        loginButton.setBorder(null);
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel2.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 100, 40));

        userLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/user.png"))); // NOI18N
        jPanel2.add(userLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 250, 160));

        jSeparator1.setForeground(new java.awt.Color(97, 212, 195));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 280, 20));

        jSeparator2.setForeground(new java.awt.Color(97, 212, 195));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 280, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 0, 440, 650));

        setSize(new java.awt.Dimension(954, 672));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed

        String username = usernameBox.getText();
        String password = passwordBox.getText();
        String sql = "SELECT * FROM adminuser WHERE username = '"+ username +"' && pass = '"+ password +"'";

        try {

            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            if(rs.next()) {

                Main m = new Main();
                m.setVisible(true);
                this.dispose();

            }
            else {

                JOptionPane.showConfirmDialog(null, "Username or Password is invalid", "ERROR", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);

            }

        }
        catch (Exception e) {

            JOptionPane.showConfirmDialog(null, e, "ERROR", JOptionPane.OK_OPTION, JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GreenUniveristy;
    private javax.swing.JLabel NSBM;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel nsbmLogo;
    private javax.swing.JPasswordField passwordBox;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel userLogo;
    private javax.swing.JTextField usernameBox;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
