/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author Chamod
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        assessmentButton = new javax.swing.JButton();
        enrollLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        enrollButton = new javax.swing.JButton();
        enrollLabel1 = new javax.swing.JLabel();
        staffButton = new javax.swing.JButton();
        enrollLabel2 = new javax.swing.JLabel();
        labButton = new javax.swing.JButton();
        enrollLabel3 = new javax.swing.JLabel();
        courseSubjectBtn = new javax.swing.JButton();
        enrollLabel4 = new javax.swing.JLabel();
        studentRecordBtn = new javax.swing.JButton();
        enrollLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NSBM Green University");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        assessmentButton.setBackground(new java.awt.Color(36, 47, 58));
        assessmentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/exam.png"))); // NOI18N
        assessmentButton.setBorderPainted(false);
        assessmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assessmentButtonActionPerformed(evt);
            }
        });
        jPanel1.add(assessmentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 140, 140));

        enrollLabel.setFont(new java.awt.Font("Trajan Pro", 1, 15)); // NOI18N
        enrollLabel.setForeground(new java.awt.Color(97, 212, 195));
        enrollLabel.setText("Student Assessment");
        jPanel1.add(enrollLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 180, 30));

        titleLabel.setFont(new java.awt.Font("Trajan Pro", 1, 26)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(97, 212, 195));
        titleLabel.setText("NSBM Student Management System");
        jPanel1.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        enrollButton.setBackground(new java.awt.Color(36, 47, 58));
        enrollButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/StudentEnroll.png"))); // NOI18N
        enrollButton.setBorder(null);
        enrollButton.setBorderPainted(false);
        enrollButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollButtonActionPerformed(evt);
            }
        });
        jPanel1.add(enrollButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 140, 140));

        enrollLabel1.setFont(new java.awt.Font("Trajan Pro", 1, 15)); // NOI18N
        enrollLabel1.setForeground(new java.awt.Color(97, 212, 195));
        enrollLabel1.setText("Courses & Subjects");
        jPanel1.add(enrollLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 180, 30));

        staffButton.setBackground(new java.awt.Color(36, 47, 58));
        staffButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/lecturer.png"))); // NOI18N
        staffButton.setBorderPainted(false);
        staffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffButtonActionPerformed(evt);
            }
        });
        jPanel1.add(staffButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 140, 140));

        enrollLabel2.setFont(new java.awt.Font("Trajan Pro", 1, 15)); // NOI18N
        enrollLabel2.setForeground(new java.awt.Color(97, 212, 195));
        enrollLabel2.setText("Student Enrollment");
        jPanel1.add(enrollLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 190, 30));

        labButton.setBackground(new java.awt.Color(36, 47, 58));
        labButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/classroom.png"))); // NOI18N
        labButton.setBorderPainted(false);
        labButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labButtonActionPerformed(evt);
            }
        });
        jPanel1.add(labButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 150, 140));

        enrollLabel3.setFont(new java.awt.Font("Trajan Pro", 1, 15)); // NOI18N
        enrollLabel3.setForeground(new java.awt.Color(97, 212, 195));
        enrollLabel3.setText("Academic Staff");
        jPanel1.add(enrollLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 180, 30));

        courseSubjectBtn.setBackground(new java.awt.Color(36, 47, 58));
        courseSubjectBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/courseSubject.png"))); // NOI18N
        courseSubjectBtn.setBorderPainted(false);
        courseSubjectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseSubjectBtnActionPerformed(evt);
            }
        });
        jPanel1.add(courseSubjectBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 140, 140));

        enrollLabel4.setFont(new java.awt.Font("Trajan Pro", 1, 15)); // NOI18N
        enrollLabel4.setForeground(new java.awt.Color(97, 212, 195));
        enrollLabel4.setText("View Student's Records");
        jPanel1.add(enrollLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 480, 220, 30));

        studentRecordBtn.setBackground(new java.awt.Color(36, 47, 58));
        studentRecordBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Search.png"))); // NOI18N
        studentRecordBtn.setBorderPainted(false);
        studentRecordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentRecordBtnActionPerformed(evt);
            }
        });
        jPanel1.add(studentRecordBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 150, 140));

        enrollLabel5.setFont(new java.awt.Font("Trajan Pro", 1, 15)); // NOI18N
        enrollLabel5.setForeground(new java.awt.Color(97, 212, 195));
        enrollLabel5.setText("Labs & ClassRooms");
        jPanel1.add(enrollLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, 180, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 580, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 650));

        setSize(new java.awt.Dimension(954, 672));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void assessmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assessmentButtonActionPerformed
        
        StudentAssessment sa = new StudentAssessment();
        sa.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_assessmentButtonActionPerformed

    private void enrollButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollButtonActionPerformed
        
        StudentEnrollment se = new StudentEnrollment();
        se.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_enrollButtonActionPerformed

    private void staffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffButtonActionPerformed
        
        AcademicStaff as = new AcademicStaff();
        as.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_staffButtonActionPerformed

    private void labButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labButtonActionPerformed
        
        LabAndClassroom lc = new LabAndClassroom();
        lc.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_labButtonActionPerformed

    private void courseSubjectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseSubjectBtnActionPerformed
        
        CoursesSubjects cs = new CoursesSubjects();
        cs.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_courseSubjectBtnActionPerformed

    private void studentRecordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentRecordBtnActionPerformed
        
        StudentRecords sr = new StudentRecords();
        sr.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_studentRecordBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assessmentButton;
    private javax.swing.JButton courseSubjectBtn;
    private javax.swing.JButton enrollButton;
    private javax.swing.JLabel enrollLabel;
    private javax.swing.JLabel enrollLabel1;
    private javax.swing.JLabel enrollLabel2;
    private javax.swing.JLabel enrollLabel3;
    private javax.swing.JLabel enrollLabel4;
    private javax.swing.JLabel enrollLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton labButton;
    private javax.swing.JButton staffButton;
    private javax.swing.JButton studentRecordBtn;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
