/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Code.ConnectDB;
import Code.PostgradStu;
import Code.Student;
import Code.UndergradStu;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Chamod
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int sid = 0;
    
    public Payment(UndergradStu u) {
        initComponents();
        
        sid = u.getStudentID();
        idLabel.setText("Student ID: "+Integer.toString(sid));
        
        con = ConnectDB.connect();
        
        try {
            int id = u.getStudentID();
            String sql = "SELECT ustu_subject.subjectId AS 'Subject ID', subject.name AS 'Subject Name', subject.price AS 'Price' FROM ustu_subject JOIN subject ON ustu_subject.subjectId = subject.subjectId WHERE ustu_subject.studentId = '"+ id +"'";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            subjectsTable.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch (Exception e) {
            JOptionPane.showConfirmDialog(null,e);
        }
        
        try {
            int id = u.getStudentID();
            String sql = "SELECT SUM(subject.price) AS 'Price' FROM ustu_subject JOIN subject ON ustu_subject.subjectId = subject.subjectId WHERE ustu_subject.studentId = '"+ id +"'";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            String total = "";
            while(rs.next()) {
                total = rs.getString("Price");
            }
            
            
            totalLabel.setText("Rs: "+total);
            
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
        
    }
    
    public Payment(PostgradStu u) {
        initComponents();
        
        sid = u.getStudentID();
        idLabel.setText("Student ID: "+Integer.toString(sid));
        
        con = ConnectDB.connect();
        
        try {
            int id = u.getStudentID();
            String sql = "SELECT pstu_subject.subjectId AS 'Subject ID', subject.name AS 'Subject Name', subject.price AS 'Price' FROM pstu_subject JOIN subject ON pstu_subject.subjectId = subject.subjectId WHERE pstu_subject.studentId = '"+ id +"'";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            subjectsTable.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch (Exception e) {
            JOptionPane.showConfirmDialog(null,e);
        }
        
        try {
            int id = u.getStudentID();
            String sql = "SELECT SUM(subject.price) AS 'Price' FROM pstu_subject JOIN subject ON pstu_subject.subjectId = subject.subjectId WHERE pstu_subject.studentId = '"+ id +"'";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            String total = "";
            while(rs.next()) {
                total = rs.getString("Price");
            }
            
            
            totalLabel.setText("Rs: "+total);
            
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
        
    }

    private Payment() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        totalLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        subjectsTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        amountBox = new javax.swing.JTextField();
        payButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));
        jPanel1.setForeground(new java.awt.Color(97, 212, 195));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalLabel.setFont(new java.awt.Font("Trajan Pro", 0, 12)); // NOI18N
        totalLabel.setForeground(new java.awt.Color(97, 212, 195));
        jPanel1.add(totalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 120, 30));

        jLabel2.setFont(new java.awt.Font("Trajan Pro", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(97, 212, 195));
        jLabel2.setText("PAYMENT");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 130, 40));

        subjectsTable.setBackground(new java.awt.Color(36, 47, 65));
        subjectsTable.setForeground(new java.awt.Color(97, 212, 195));
        subjectsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject ID", "Subject Name", "Price"
            }
        ));
        jScrollPane1.setViewportView(subjectsTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 350, 290));

        jLabel3.setFont(new java.awt.Font("Trajan Pro", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(97, 212, 195));
        jLabel3.setText("Subjects You Enrolled");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 320, 40));

        jLabel4.setFont(new java.awt.Font("Trajan Pro", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(97, 212, 195));
        jLabel4.setText("ToTal Payment for 1st Semester:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 270, 30));

        idLabel.setForeground(new java.awt.Color(97, 212, 195));
        jPanel1.add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 140, 20));

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(97, 212, 195));
        jLabel1.setText("Amount:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, -1));
        jPanel1.add(amountBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 110, 30));

        payButton.setText("PAY");
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });
        jPanel1.add(payButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 100, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed
        
        double amount = Double.parseDouble(amountBox.getText());
        int id = sid;
        String payedDate = java.time.LocalDate.now().toString();
        
        if(amount < 12000) {
            JOptionPane.showConfirmDialog(null, "Please make a payment higher than Rs:12000", "Payment Not Sufficient", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            
            con = ConnectDB.connect();
            
            try {
                
                String sql = "INSERT INTO payment (studentId, payedAmount, payedDay) VALUES ('"+ id +"', '"+ amount +"', '"+ payedDate +"')";
                pst = con.prepareStatement(sql);
                pst.execute();
            }
            catch (Exception e) {
                JOptionPane.showConfirmDialog(null, e);
            }
            
            JOptionPane.showConfirmDialog(null, "Payment Successfull", "Payment Done", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            StudentEnrollment se = new StudentEnrollment();
            se.setVisible(true);
        }
        
    }//GEN-LAST:event_payButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountBox;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton payButton;
    private javax.swing.JTable subjectsTable;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
