/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Code.ConnectDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Chamod
 */
public class StudentRecords extends javax.swing.JFrame {

    /**
     * Creates new form StudentRecords
     */
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public StudentRecords() {
        initComponents();
        
        con = ConnectDB.connect();
        
        tableLoadUDetails();
        tableLoadPDetails();
        tableLoadPayment();
        tableLoadAssessmentTable();
        
    }
    
    public void tableLoadUDetails() {
    
        try {
            
            String sql = "SELECT sId AS 'Student ID', name AS 'Name', dob AS 'DOB', gender AS 'Gender', NIC As 'NIC', civilStatus AS 'Civil Status', address AS 'Address', phoneNo AS 'Phone NO', email AS 'Email', alResult AS 'AL Result', alRank AS 'AL Rank' FROM undergradStu";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            sdDetailsTable.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    
    }
    
    public void tableLoadPDetails() {
    
        try {
            
            String sql = "SELECT sId AS 'Student ID', name AS 'Name', dob AS 'DOB', gender AS 'Gender', NIC As 'NIC', civilStatus AS 'Civil Status', address AS 'Address', phoneNo AS 'Phone NO', email AS 'Email', qualification AS 'Qualification', passedYear AS 'Passed Year', institute AS 'Institute' FROM postgradStu";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            sdDetailspTable.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    
    }
    
    public void tableLoadPayment() {
    
        try {
            
            String sql = "SELECT paymentId AS 'Payment ID', studentId AS 'Student ID', payedAmount AS 'Payed Amount', payedDay AS 'Payed Date' FROM payment";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            paymentTable.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    
    }
    
    public void tableLoadAssessmentTable() {
    
        try {
            
            String sql = "SELECT * FROM assessmentView";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            assessmentTable.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LeftPanel = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        backButton1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        paymentBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        RightPanel = new javax.swing.JPanel();
        StudentDetails = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        sdSid = new javax.swing.JTextField();
        sdSearchBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        sdDetailsTable = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sdDetailspTable = new javax.swing.JTable();
        sdSidp = new javax.swing.JTextField();
        sdSearchpBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        sdShowAllBtn = new javax.swing.JButton();
        sdShowAllpBtn = new javax.swing.JButton();
        PaymentDetails = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        pdSid = new javax.swing.JTextField();
        pdShowAllBtn = new javax.swing.JButton();
        pdSearchBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        paymentTable = new javax.swing.JTable();
        AssessmentDetails = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        adSid = new javax.swing.JTextField();
        adShowAllBtn = new javax.swing.JButton();
        adSearchBtn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        assessmentTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LeftPanel.setBackground(new java.awt.Color(209, 246, 251));
        LeftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/homeIcon.png"))); // NOI18N
        homeButton.setBorder(null);
        homeButton.setBorderPainted(false);
        homeButton.setContentAreaFilled(false);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        LeftPanel.add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        backButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/backIcon.png"))); // NOI18N
        backButton1.setBorder(null);
        backButton1.setBorderPainted(false);
        backButton1.setContentAreaFilled(false);
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });
        LeftPanel.add(backButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jButton1.setText("STUDENT DETAILS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        LeftPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 160, 50));

        paymentBtn.setText("PAYMENT DETAILS");
        paymentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentBtnActionPerformed(evt);
            }
        });
        LeftPanel.add(paymentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 160, 50));

        jButton2.setText("ASSESSMENT DETAILS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        LeftPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 160, 50));

        getContentPane().add(LeftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 650));

        RightPanel.setBackground(new java.awt.Color(36, 47, 65));
        RightPanel.setLayout(new java.awt.CardLayout());

        StudentDetails.setBackground(new java.awt.Color(36, 47, 65));
        StudentDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(209, 246, 251));
        jLabel7.setText("Undergraduate Students");
        StudentDetails.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 400, 30));
        StudentDetails.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 640, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(209, 246, 251));
        jLabel1.setText("Student ID");
        StudentDetails.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, 30));

        sdSid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdSidActionPerformed(evt);
            }
        });
        StudentDetails.add(sdSid, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 190, 30));

        sdSearchBtn.setText("SEARCH");
        sdSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdSearchBtnActionPerformed(evt);
            }
        });
        StudentDetails.add(sdSearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 110, 40));

        sdDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(sdDetailsTable);

        StudentDetails.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 700, 160));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(209, 246, 251));
        jLabel8.setText("Student Details");
        StudentDetails.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 400, 30));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(209, 246, 251));
        jLabel2.setText("Student ID");
        StudentDetails.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, -1, 30));

        sdDetailspTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(sdDetailspTable);

        StudentDetails.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 700, 160));

        sdSidp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdSidpActionPerformed(evt);
            }
        });
        StudentDetails.add(sdSidp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 190, 30));

        sdSearchpBtn.setText("SEARCH");
        sdSearchpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdSearchpBtnActionPerformed(evt);
            }
        });
        StudentDetails.add(sdSearchpBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 110, 40));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(209, 246, 251));
        jLabel9.setText("Postgraduate Students");
        StudentDetails.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 400, 30));

        sdShowAllBtn.setText("SHOW ALL");
        sdShowAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdShowAllBtnActionPerformed(evt);
            }
        });
        StudentDetails.add(sdShowAllBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 110, 40));

        sdShowAllpBtn.setText("SHOW ALL");
        sdShowAllpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdShowAllpBtnActionPerformed(evt);
            }
        });
        StudentDetails.add(sdShowAllpBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 110, 40));

        RightPanel.add(StudentDetails, "card2");

        PaymentDetails.setBackground(new java.awt.Color(36, 47, 65));
        PaymentDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(209, 246, 251));
        jLabel10.setText("Student Payment Details");
        PaymentDetails.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 400, 30));
        PaymentDetails.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 640, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(209, 246, 251));
        jLabel3.setText("Student ID");
        PaymentDetails.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 30));
        PaymentDetails.add(pdSid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 210, 30));

        pdShowAllBtn.setText("SHOW ALL");
        pdShowAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdShowAllBtnActionPerformed(evt);
            }
        });
        PaymentDetails.add(pdShowAllBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 120, 50));

        pdSearchBtn.setText("SEARCH");
        pdSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdSearchBtnActionPerformed(evt);
            }
        });
        PaymentDetails.add(pdSearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 120, 50));

        paymentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(paymentTable);

        PaymentDetails.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        RightPanel.add(PaymentDetails, "card3");

        AssessmentDetails.setBackground(new java.awt.Color(36, 47, 65));
        AssessmentDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(209, 246, 251));
        jLabel11.setText("Assessment Details");
        AssessmentDetails.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 400, 30));
        AssessmentDetails.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 640, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(209, 246, 251));
        jLabel4.setText("Student ID");
        AssessmentDetails.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, 30));
        AssessmentDetails.add(adSid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 210, 30));

        adShowAllBtn.setText("SHOW ALL");
        adShowAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adShowAllBtnActionPerformed(evt);
            }
        });
        AssessmentDetails.add(adShowAllBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 110, 50));

        adSearchBtn.setText("SEARCH");
        adSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adSearchBtnActionPerformed(evt);
            }
        });
        AssessmentDetails.add(adSearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 110, 50));

        assessmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(assessmentTable);

        AssessmentDetails.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 640, -1));

        RightPanel.add(AssessmentDetails, "card4");

        getContentPane().add(RightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 730, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed

        Main m = new Main();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed

        Main m = new Main();
        m.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_backButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        RightPanel.removeAll();
        RightPanel.repaint();
        RightPanel.revalidate();

        RightPanel.add(StudentDetails);
        RightPanel.repaint();
        RightPanel.revalidate();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sdSidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdSidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sdSidActionPerformed

    private void sdSidpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdSidpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sdSidpActionPerformed

    private void sdSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdSearchBtnActionPerformed
        
        if(sdSid.getText().isEmpty()) {
        
            JOptionPane.showConfirmDialog(null, "Please Enter a Student ID", "Student ID is Empty!", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
        
        }
        else {
            
            String sId = sdSid.getText();
        
            try {
            
            String sql = "SELECT sId AS 'Student ID', name AS 'Name', dob AS 'DOB', gender AS 'Gender', NIC As 'NIC', civilStatus AS 'Civil Status', address AS 'Address', phoneNo AS 'Phone NO', email AS 'Email', alResult AS 'AL Result', alRank AS 'AL Rank' FROM undergradStu WHERE sId = '"+ sId +"'";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            sdDetailsTable.setModel(DbUtils.resultSetToTableModel(rs));
            
            }
            catch (Exception e) {
                JOptionPane.showConfirmDialog(null, e);
            }
        
        }
        
    }//GEN-LAST:event_sdSearchBtnActionPerformed

    private void sdShowAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdShowAllBtnActionPerformed
        
        tableLoadUDetails();
        
    }//GEN-LAST:event_sdShowAllBtnActionPerformed

    private void sdSearchpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdSearchpBtnActionPerformed
        
        if(sdSidp.getText().isEmpty()) {
        
            JOptionPane.showConfirmDialog(null, "Please Enter a Student ID", "Student ID is Empty!", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
        
        }
        else {
            
            String sId = sdSidp.getText();
        
            try {
            
            String sql = "SELECT sId AS 'Student ID', name AS 'Name', dob AS 'DOB', gender AS 'Gender', NIC As 'NIC', civilStatus AS 'Civil Status', address AS 'Address', phoneNo AS 'Phone NO', email AS 'Email', qualification AS 'Qualification', passedYear AS 'Passed Year', institute AS 'Institute' FROM postgradStu WHERE sId = '"+ sId +"'";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            sdDetailspTable.setModel(DbUtils.resultSetToTableModel(rs));
            
            }
            catch (Exception e) {
                JOptionPane.showConfirmDialog(null, e);
            }
        
        }
        
    }//GEN-LAST:event_sdSearchpBtnActionPerformed

    private void sdShowAllpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdShowAllpBtnActionPerformed
        
        tableLoadPDetails();
        
    }//GEN-LAST:event_sdShowAllpBtnActionPerformed

    private void paymentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentBtnActionPerformed
        
        RightPanel.removeAll();
        RightPanel.repaint();
        RightPanel.revalidate();

        RightPanel.add(PaymentDetails);
        RightPanel.repaint();
        RightPanel.revalidate();
        
    }//GEN-LAST:event_paymentBtnActionPerformed

    private void pdSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdSearchBtnActionPerformed
        
        if(pdSid.getText().isEmpty()) {
        
            JOptionPane.showConfirmDialog(null, "Please Enter a Student ID", "Student ID is Empty!", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
        
        }
        else {
            
            String sId = pdSid.getText();
        
            try {
            
            String sql = "SELECT paymentId AS 'Payment ID', studentId AS 'Student ID', payedAmount AS 'Payed Amount', payedDay AS 'Payed Date' FROM payment WHERE studentId = '"+ sId +"'";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            paymentTable.setModel(DbUtils.resultSetToTableModel(rs));
            
            }
            catch (Exception e) {
                JOptionPane.showConfirmDialog(null, e);
            }
        
        }
        
    }//GEN-LAST:event_pdSearchBtnActionPerformed

    private void pdShowAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdShowAllBtnActionPerformed
        
        tableLoadPayment();
        
    }//GEN-LAST:event_pdShowAllBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        RightPanel.removeAll();
        RightPanel.repaint();
        RightPanel.revalidate();

        RightPanel.add(AssessmentDetails);
        RightPanel.repaint();
        RightPanel.revalidate();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void adSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adSearchBtnActionPerformed
        
        if(adSid.getText().isEmpty()) {
        
            JOptionPane.showConfirmDialog(null, "Please Enter a Student ID", "Student ID is Empty!", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
        
        }
        else {
            
            String sId = adSid.getText();
        
            try {
            
            String sql = "SELECT * FROM assessmentView WHERE `Student ID` = '"+ sId +"'";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            assessmentTable.setModel(DbUtils.resultSetToTableModel(rs));
            
            }
            catch (Exception e) {
                JOptionPane.showConfirmDialog(null, e);
            }
        
        }
        
    }//GEN-LAST:event_adSearchBtnActionPerformed

    private void adShowAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adShowAllBtnActionPerformed
        
        tableLoadAssessmentTable();
        
    }//GEN-LAST:event_adShowAllBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentRecords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AssessmentDetails;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JPanel PaymentDetails;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JPanel StudentDetails;
    private javax.swing.JButton adSearchBtn;
    private javax.swing.JButton adShowAllBtn;
    private javax.swing.JTextField adSid;
    private javax.swing.JTable assessmentTable;
    private javax.swing.JButton backButton1;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton paymentBtn;
    private javax.swing.JTable paymentTable;
    private javax.swing.JButton pdSearchBtn;
    private javax.swing.JButton pdShowAllBtn;
    private javax.swing.JTextField pdSid;
    private javax.swing.JTable sdDetailsTable;
    private javax.swing.JTable sdDetailspTable;
    private javax.swing.JButton sdSearchBtn;
    private javax.swing.JButton sdSearchpBtn;
    private javax.swing.JButton sdShowAllBtn;
    private javax.swing.JButton sdShowAllpBtn;
    private javax.swing.JTextField sdSid;
    private javax.swing.JTextField sdSidp;
    // End of variables declaration//GEN-END:variables
}
