/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Code.AssessmentType;
import Code.ConnectDB;
import Code.StuAssessment;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Chamod
 */
public class StudentAssessment extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public StudentAssessment() {
        initComponents();
        
        con = ConnectDB.connect();
        tableLoad();
        tableLoadat();
        
    }
    
    // load stu_assess table
    public void tableLoad(){
        
        try {
            
            String sql = "SELECT studentId AS 'Student ID', assessmentId AS 'Assessment ID', marks AS 'Marks' FROM stu_assess";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            assessmentTable.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
        
    }
    
    // load assessment table
    public void tableLoadat(){
        
        try {
            
            String sql = "SELECT id AS 'Assessment ID', type AS 'Assessment Type', subjectId AS 'Subject ID' FROM assessment";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            atTable.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LeftPanel = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        backButton1 = new javax.swing.JButton();
        updateAssButton = new javax.swing.JButton();
        addAssButton = new javax.swing.JButton();
        assTypesButton = new javax.swing.JButton();
        RightPanel = new javax.swing.JPanel();
        AddAssessment = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        assessmentIDBox = new javax.swing.JTextField();
        marksBox = new javax.swing.JTextField();
        studentIDBox = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        UpdateAssessment = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        assessmentTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        markBox = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        sidBox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        assBox = new javax.swing.JTextField();
        searchButton1 = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        AssessmentTypes = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        atAssTypeBox = new javax.swing.JTextField();
        atSubIdBox = new javax.swing.JTextField();
        atAssIdBox = new javax.swing.JTextField();
        atAddButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        atTable = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        atSubId2Box = new javax.swing.JTextField();
        atAssId2Box = new javax.swing.JTextField();
        atAssType2Box = new javax.swing.JTextField();
        atDeleteButton = new javax.swing.JButton();
        atUpdateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LeftPanel.setBackground(new java.awt.Color(209, 246, 251));
        LeftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/homeIcon.png"))); // NOI18N
        homeButton.setBorder(null);
        homeButton.setBorderPainted(false);
        homeButton.setContentAreaFilled(false);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        LeftPanel.add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        backButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/backIcon.png"))); // NOI18N
        backButton1.setBorder(null);
        backButton1.setBorderPainted(false);
        backButton1.setContentAreaFilled(false);
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });
        LeftPanel.add(backButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        updateAssButton.setText("UPDATE");
        updateAssButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAssButtonActionPerformed(evt);
            }
        });
        LeftPanel.add(updateAssButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 150, 50));

        addAssButton.setText("ADD");
        addAssButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAssButtonActionPerformed(evt);
            }
        });
        LeftPanel.add(addAssButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 150, 50));

        assTypesButton.setText("ASSESSMENT TYPES");
        assTypesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assTypesButtonActionPerformed(evt);
            }
        });
        LeftPanel.add(assTypesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 150, 50));

        getContentPane().add(LeftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 650));

        RightPanel.setBackground(new java.awt.Color(36, 47, 65));
        RightPanel.setLayout(new java.awt.CardLayout());

        AddAssessment.setBackground(new java.awt.Color(36, 47, 65));
        AddAssessment.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(209, 246, 251));
        jLabel1.setText("Assessment ID");
        AddAssessment.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 100, 30));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(209, 246, 251));
        jLabel2.setText("Marks");
        AddAssessment.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 100, 30));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(209, 246, 251));
        jLabel3.setText("Student ID");
        AddAssessment.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 100, 30));
        AddAssessment.add(assessmentIDBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 180, 30));
        AddAssessment.add(marksBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 180, 30));
        AddAssessment.add(studentIDBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 180, 30));

        submitButton.setText("SUBMIT");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        AddAssessment.add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 100, 40));
        AddAssessment.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 640, -1));

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(209, 246, 251));
        jLabel15.setText("Add Student Assessment");
        AddAssessment.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 400, 30));

        RightPanel.add(AddAssessment, "card2");

        UpdateAssessment.setBackground(new java.awt.Color(36, 47, 65));
        UpdateAssessment.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        assessmentTable.setBackground(new java.awt.Color(36, 47, 65));
        assessmentTable.setForeground(new java.awt.Color(209, 246, 251));
        assessmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Student ID", "Assessment ID", "Marks"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        assessmentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                assessmentTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(assessmentTable);

        UpdateAssessment.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 360, 460));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(209, 246, 251));
        jLabel4.setText("Marks");
        UpdateAssessment.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 100, 30));
        UpdateAssessment.add(markBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 180, 30));

        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        UpdateAssessment.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 110, 40));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(209, 246, 251));
        jLabel5.setText("Student ID");
        UpdateAssessment.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 100, 30));
        UpdateAssessment.add(sidBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 180, 30));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(209, 246, 251));
        jLabel6.setText("Assessment ID");
        UpdateAssessment.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 100, 30));
        UpdateAssessment.add(assBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 180, 30));

        searchButton1.setText("SEARCH");
        UpdateAssessment.add(searchButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, 100, 30));

        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        UpdateAssessment.add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 110, 40));

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(209, 246, 251));
        jLabel16.setText("Update Student Assessment");
        UpdateAssessment.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 400, 30));
        UpdateAssessment.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 640, -1));

        RightPanel.add(UpdateAssessment, "card3");

        AssessmentTypes.setBackground(new java.awt.Color(36, 47, 65));
        AssessmentTypes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(209, 246, 251));
        jLabel7.setText("Add New Assessment Type");
        AssessmentTypes.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 400, 30));
        AssessmentTypes.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 640, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(209, 246, 251));
        jLabel8.setText("Subject ID");
        AssessmentTypes.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, -1, 20));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(209, 246, 251));
        jLabel9.setText("Assessment ID");
        AssessmentTypes.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, -1, 20));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(209, 246, 251));
        jLabel10.setText("Assessment Type");
        AssessmentTypes.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, -1, 30));
        AssessmentTypes.add(atAssTypeBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 130, 30));
        AssessmentTypes.add(atSubIdBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 80, 30));
        AssessmentTypes.add(atAssIdBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 90, 30));

        atAddButton.setText("ADD");
        atAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atAddButtonActionPerformed(evt);
            }
        });
        AssessmentTypes.add(atAddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 110, 40));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(209, 246, 251));
        jLabel11.setText("Manage Assessment Types");
        AssessmentTypes.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 400, 30));
        AssessmentTypes.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 640, -1));

        atTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        atTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(atTable);

        AssessmentTypes.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 380, 380));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(209, 246, 251));
        jLabel12.setText("Assessment ID");
        AssessmentTypes.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, 30));

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(209, 246, 251));
        jLabel13.setText("Assessment Type");
        AssessmentTypes.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, 30));

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(209, 246, 251));
        jLabel14.setText("Subject ID");
        AssessmentTypes.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 97, -1, 20));

        atSubId2Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atSubId2BoxActionPerformed(evt);
            }
        });
        AssessmentTypes.add(atSubId2Box, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 140, 30));

        atAssId2Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atAssId2BoxActionPerformed(evt);
            }
        });
        AssessmentTypes.add(atAssId2Box, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 140, 30));

        atAssType2Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atAssType2BoxActionPerformed(evt);
            }
        });
        AssessmentTypes.add(atAssType2Box, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 140, 30));

        atDeleteButton.setText("DELETE");
        atDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atDeleteButtonActionPerformed(evt);
            }
        });
        AssessmentTypes.add(atDeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 530, 120, 40));

        atUpdateButton.setText("UPDATE");
        atUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atUpdateButtonActionPerformed(evt);
            }
        });
        AssessmentTypes.add(atUpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, 120, 40));

        RightPanel.add(AssessmentTypes, "card4");

        getContentPane().add(RightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 730, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed

        Main m = new Main();
        m.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_homeButtonActionPerformed

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed

        Main m = new Main();
        m.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_backButton1ActionPerformed

    private void updateAssButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAssButtonActionPerformed

        RightPanel.removeAll();
        RightPanel.repaint();
        RightPanel.revalidate();

        RightPanel.add(UpdateAssessment);
        RightPanel.repaint();
        RightPanel.revalidate();
        
      

    }//GEN-LAST:event_updateAssButtonActionPerformed

    private void addAssButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAssButtonActionPerformed

        RightPanel.removeAll();
        RightPanel.repaint();
        RightPanel.revalidate();

        RightPanel.add(AddAssessment);
        RightPanel.repaint();
        RightPanel.revalidate();

    }//GEN-LAST:event_addAssButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        
        if(studentIDBox.getText().isEmpty() || assessmentIDBox.getText().isEmpty() || marksBox.getText().isEmpty()) {
            JOptionPane.showConfirmDialog(null, "Please Fill All Fields", "Fields are Empty!", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            
            String sid = studentIDBox.getText();
            String assid = assessmentIDBox.getText();
            int marks = Integer.parseInt(marksBox.getText());
            
            StuAssessment sa = new StuAssessment(sid, assid, marks);
            sa.addStuAssess();
            
            studentIDBox.setText("");
            assessmentIDBox.setText("");
            marksBox.setText("");
            tableLoad();
            
        }
        
    }//GEN-LAST:event_submitButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        
        int x = JOptionPane.showConfirmDialog(null, "Do you want to delete the record?");
        
        if(x==0) {
        
            String sid = sidBox.getText();
            StuAssessment sa = new StuAssessment(sid);
            sa.deleteStuAssess();
            
            
            tableLoad();

            sidBox.setText("");
            assBox.setText("");
            markBox.setText("");
        
        }
        
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void assessmentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assessmentTableMouseClicked
        
        int r = assessmentTable.getSelectedRow();
        
        String studentId = assessmentTable.getValueAt(r, 0).toString();
        String assessmentId = assessmentTable.getValueAt(r, 1).toString();
        String marks = assessmentTable.getValueAt(r, 2).toString();
        
        sidBox.setText(studentId);
        assBox.setText(assessmentId);
        markBox.setText(marks);
        
    }//GEN-LAST:event_assessmentTableMouseClicked

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        
        int x = JOptionPane.showConfirmDialog(null, "Do you want to update this record?");
        
        String sid = sidBox.getText();
        String assid = assBox.getText();
        int marks = Integer.parseInt(markBox.getText());
        
        if(x==0) {
        
            StuAssessment sa = new StuAssessment(sid, assid, marks);
            sa.updateStuAssess();
                
            tableLoad();

            sidBox.setText("");
            assBox.setText("");
            markBox.setText("");
                    
        }
        
    }//GEN-LAST:event_updateButtonActionPerformed

    private void assTypesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assTypesButtonActionPerformed
        
        RightPanel.removeAll();
        RightPanel.repaint();
        RightPanel.revalidate();

        RightPanel.add(AssessmentTypes);
        RightPanel.repaint();
        RightPanel.revalidate();
        
    }//GEN-LAST:event_assTypesButtonActionPerformed

    private void atSubId2BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atSubId2BoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atSubId2BoxActionPerformed

    private void atAssId2BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atAssId2BoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atAssId2BoxActionPerformed

    private void atAssType2BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atAssType2BoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atAssType2BoxActionPerformed

    private void atAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atAddButtonActionPerformed
        
        if(atAssIdBox.getText().isEmpty() || atAssTypeBox.getText().isEmpty() || atSubIdBox.getText().isEmpty()) {
            JOptionPane.showConfirmDialog(null, "Please Fill All Fields", "Fields are Empty!", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            
            String assId = atAssIdBox.getText();
            String assType = atAssTypeBox.getText();
            String subId = atSubIdBox.getText();
            
            AssessmentType at = new AssessmentType(assId, assType, subId);
            at.add();
            
            atAssIdBox.setText("");
            atAssTypeBox.setText("");
            atSubIdBox.setText("");
            tableLoadat();
            
        }
        
    }//GEN-LAST:event_atAddButtonActionPerformed

    private void atTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atTableMouseClicked
        
        int r = atTable.getSelectedRow();
        
        String assId = atTable.getValueAt(r, 0).toString();
        String assType = atTable.getValueAt(r, 1).toString();
        String subId = atTable.getValueAt(r, 2).toString();
        
        atAssId2Box.setText(assId);
        atAssType2Box.setText(assType);
        atSubId2Box.setText(subId);
        
    }//GEN-LAST:event_atTableMouseClicked

    private void atUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atUpdateButtonActionPerformed
        
        int x = JOptionPane.showConfirmDialog(null, "Do you want to update this record?");
        
        String assId = atAssId2Box.getText();
        String assType = atAssType2Box.getText();
        String subId = atSubId2Box.getText();
        
        if(x==0) {
        
            AssessmentType at = new AssessmentType(assId, assType, subId);
            at.update();
                
            tableLoadat();

            atAssId2Box.setText("");
            atAssType2Box.setText("");
            atSubId2Box.setText("");
                
        }
        
    }//GEN-LAST:event_atUpdateButtonActionPerformed

    private void atDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atDeleteButtonActionPerformed
        
        int x = JOptionPane.showConfirmDialog(null, "Do you want to delete this record?");
        
        if(x==0) {
        
            String assId = atAssId2Box.getText();
            AssessmentType at = new AssessmentType(assId);
            at.delete();
                
            tableLoadat();

            atAssId2Box.setText("");
            atAssType2Box.setText("");
            atSubId2Box.setText("");
                
        }
        
    }//GEN-LAST:event_atDeleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentAssessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentAssessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentAssessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentAssessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentAssessment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddAssessment;
    private javax.swing.JPanel AssessmentTypes;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JPanel UpdateAssessment;
    private javax.swing.JButton addAssButton;
    private javax.swing.JTextField assBox;
    private javax.swing.JButton assTypesButton;
    private javax.swing.JTextField assessmentIDBox;
    private javax.swing.JTable assessmentTable;
    private javax.swing.JButton atAddButton;
    private javax.swing.JTextField atAssId2Box;
    private javax.swing.JTextField atAssIdBox;
    private javax.swing.JTextField atAssType2Box;
    private javax.swing.JTextField atAssTypeBox;
    private javax.swing.JButton atDeleteButton;
    private javax.swing.JTextField atSubId2Box;
    private javax.swing.JTextField atSubIdBox;
    private javax.swing.JTable atTable;
    private javax.swing.JButton atUpdateButton;
    private javax.swing.JButton backButton1;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField markBox;
    private javax.swing.JTextField marksBox;
    private javax.swing.JButton searchButton1;
    private javax.swing.JTextField sidBox;
    private javax.swing.JTextField studentIDBox;
    private javax.swing.JButton submitButton;
    private javax.swing.JButton updateAssButton;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
