/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Code.ConnectDB;
import Code.PostgradStu;
import Code.StuPayments;
import Code.StudentSubjects;
import Code.UndergradStu;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Chamod
 */
public class StudentEnrollment extends javax.swing.JFrame {

    /**
     * Creates new form StudentEnrollment
     */
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public StudentEnrollment() {
        
        initComponents();
        
        con = ConnectDB.connect();
        tableLoadPayment();
        tableLoadUndergradSub();
        tableLoadPostgradSub();
        
    }
    
    public void tableLoadPayment() {
    
        try {
            
            String sql = "SELECT paymentId AS 'Payment ID', studentId AS 'Student ID', payedAmount AS 'Payed Amount', payedDay AS 'Payed Date' FROM payment";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            paymentTable.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    
    }
    
    public void tableLoadUndergradSub() {
    
        try {
            
            String sql = "SELECT studentId AS 'Student ID', subjectId AS 'Subject ID' FROM ustu_subject";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            useTable.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    
    }
    
    public void tableLoadPostgradSub() {
    
        try {
            
            String sql = "SELECT studentId AS 'Student ID', subjectId AS 'Subject ID' FROM pstu_subject";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            pseTable.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        civilButtonGroup = new javax.swing.ButtonGroup();
        RightPanel = new javax.swing.JPanel();
        AddUndergraduate = new javax.swing.JPanel();
        alRankLabel2 = new javax.swing.JLabel();
        nameLabel3 = new javax.swing.JLabel();
        dobLabel4 = new javax.swing.JLabel();
        nameLabel18 = new javax.swing.JLabel();
        nameLabel19 = new javax.swing.JLabel();
        nameLabel20 = new javax.swing.JLabel();
        nameLabel21 = new javax.swing.JLabel();
        nameBox = new javax.swing.JTextField();
        maleRadioButton = new javax.swing.JRadioButton();
        femaleRadioButton = new javax.swing.JRadioButton();
        dobBox = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        addressBox = new javax.swing.JTextArea();
        alSub3Box = new javax.swing.JTextField();
        alRankBox = new javax.swing.JTextField();
        singleRadioButton = new javax.swing.JRadioButton();
        marriedRadioButton = new javax.swing.JRadioButton();
        nameLabel22 = new javax.swing.JLabel();
        phoneBox = new javax.swing.JTextField();
        alSub1Box = new javax.swing.JTextField();
        alSub2Box = new javax.swing.JTextField();
        alResultLabel3 = new javax.swing.JLabel();
        emailBox = new javax.swing.JTextField();
        nextButton = new javax.swing.JButton();
        nameLabel23 = new javax.swing.JLabel();
        dobLabel5 = new javax.swing.JLabel();
        nicBox = new javax.swing.JTextField();
        nameLabel24 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        AddUndergraduate2 = new javax.swing.JPanel();
        au2enrollButton = new javax.swing.JButton();
        subject1Label = new javax.swing.JLabel();
        courseComboBox = new javax.swing.JComboBox<>();
        intakeLabel = new javax.swing.JLabel();
        sem1subLabel = new javax.swing.JLabel();
        sem1sub5 = new javax.swing.JCheckBox();
        sem1sub1 = new javax.swing.JCheckBox();
        sem1sub2 = new javax.swing.JCheckBox();
        sem1sub3 = new javax.swing.JCheckBox();
        sem1sub4 = new javax.swing.JCheckBox();
        sem2sub1 = new javax.swing.JCheckBox();
        sem2sub2 = new javax.swing.JCheckBox();
        sem2sub3 = new javax.swing.JCheckBox();
        sem2sub4 = new javax.swing.JCheckBox();
        sem2sub5 = new javax.swing.JCheckBox();
        au2backButton1 = new javax.swing.JButton();
        courseLabel2 = new javax.swing.JLabel();
        intakeComboBox = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        AddPostgraduate = new javax.swing.JPanel();
        alRankLabel3 = new javax.swing.JLabel();
        nameLabel4 = new javax.swing.JLabel();
        dobLabel6 = new javax.swing.JLabel();
        nameLabel25 = new javax.swing.JLabel();
        nameLabel26 = new javax.swing.JLabel();
        nameLabel27 = new javax.swing.JLabel();
        nameLabel28 = new javax.swing.JLabel();
        nameBox1 = new javax.swing.JTextField();
        maleRadioButton1 = new javax.swing.JRadioButton();
        femaleRadioButton1 = new javax.swing.JRadioButton();
        dobBox1 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        addressBox1 = new javax.swing.JTextArea();
        instituteBox = new javax.swing.JTextField();
        singleRadioButton1 = new javax.swing.JRadioButton();
        marriedRadioButton1 = new javax.swing.JRadioButton();
        phoneBox1 = new javax.swing.JTextField();
        qualificationBox = new javax.swing.JTextField();
        yearCompletedBox = new javax.swing.JTextField();
        alResultLabel4 = new javax.swing.JLabel();
        emailBox1 = new javax.swing.JTextField();
        nextButton1 = new javax.swing.JButton();
        nameLabel30 = new javax.swing.JLabel();
        dobLabel7 = new javax.swing.JLabel();
        nicBox1 = new javax.swing.JTextField();
        nameLabel31 = new javax.swing.JLabel();
        alResultLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        AddPostgraduate2 = new javax.swing.JPanel();
        ap2EnrollButton = new javax.swing.JButton();
        subject1Label1 = new javax.swing.JLabel();
        courseComboBox1 = new javax.swing.JComboBox<>();
        intakeLabel1 = new javax.swing.JLabel();
        sem1subLabel1 = new javax.swing.JLabel();
        ap2BackButton = new javax.swing.JButton();
        courseLabel3 = new javax.swing.JLabel();
        intakeComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        sem2subjects = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        sem1subjects = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        Payment = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane5 = new javax.swing.JScrollPane();
        paymentTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        pDateBox = new javax.swing.JTextField();
        paymentIdLabel = new javax.swing.JLabel();
        pSidBox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pAmountBox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pDeleteBtn = new javax.swing.JButton();
        pAddBtn = new javax.swing.JButton();
        SubjectEnrollments = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        useTable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        seSubId = new javax.swing.JTextField();
        seSid = new javax.swing.JTextField();
        seDeleteBtn = new javax.swing.JButton();
        seAddBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        pseTable = new javax.swing.JTable();
        sepSid = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        sepSubId = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        sepAddBtn = new javax.swing.JButton();
        sepDeleteBtn = new javax.swing.JButton();
        LeftPanel = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        backButton1 = new javax.swing.JButton();
        addPButton = new javax.swing.JButton();
        addUButton = new javax.swing.JButton();
        paymentBtn = new javax.swing.JButton();
        subjectEnrollmentBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RightPanel.setBackground(new java.awt.Color(36, 47, 65));
        RightPanel.setLayout(new java.awt.CardLayout());

        AddUndergraduate.setBackground(new java.awt.Color(36, 47, 65));
        AddUndergraduate.setPreferredSize(new java.awt.Dimension(660, 620));
        AddUndergraduate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        alRankLabel2.setForeground(new java.awt.Color(209, 246, 251));
        alRankLabel2.setText("A/L Rank");
        AddUndergraduate.add(alRankLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, -1, -1));

        nameLabel3.setForeground(new java.awt.Color(209, 246, 251));
        nameLabel3.setText("Name");
        AddUndergraduate.add(nameLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 60, 30));

        dobLabel4.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        dobLabel4.setForeground(new java.awt.Color(209, 246, 251));
        dobLabel4.setText("YYYY-MM-DD");
        AddUndergraduate.add(dobLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        nameLabel18.setForeground(new java.awt.Color(209, 246, 251));
        nameLabel18.setText("Address");
        AddUndergraduate.add(nameLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        nameLabel19.setForeground(new java.awt.Color(209, 246, 251));
        nameLabel19.setText("NIC");
        AddUndergraduate.add(nameLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        nameLabel20.setForeground(new java.awt.Color(209, 246, 251));
        nameLabel20.setText("E-mail");
        AddUndergraduate.add(nameLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 90, 20));

        nameLabel21.setForeground(new java.awt.Color(209, 246, 251));
        nameLabel21.setText("Phone No");
        AddUndergraduate.add(nameLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 90, 20));
        AddUndergraduate.add(nameBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 250, 30));

        genderButtonGroup.add(maleRadioButton);
        maleRadioButton.setForeground(new java.awt.Color(209, 246, 251));
        maleRadioButton.setText("Male");
        maleRadioButton.setActionCommand("M");
        AddUndergraduate.add(maleRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 80, 30));

        genderButtonGroup.add(femaleRadioButton);
        femaleRadioButton.setForeground(new java.awt.Color(209, 246, 251));
        femaleRadioButton.setText("Female");
        femaleRadioButton.setActionCommand("F");
        AddUndergraduate.add(femaleRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 90, 30));
        AddUndergraduate.add(dobBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 100, 30));

        addressBox.setColumns(20);
        addressBox.setRows(4);
        addressBox.setPreferredSize(new java.awt.Dimension(200, 50));
        addressBox.setSize(new java.awt.Dimension(220, 50));
        jScrollPane3.setViewportView(addressBox);

        AddUndergraduate.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 270, 90));
        AddUndergraduate.add(alSub3Box, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, 200, 30));
        AddUndergraduate.add(alRankBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 590, 130, 30));

        civilButtonGroup.add(singleRadioButton);
        singleRadioButton.setForeground(new java.awt.Color(209, 246, 251));
        singleRadioButton.setText("Single");
        AddUndergraduate.add(singleRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 80, 30));

        civilButtonGroup.add(marriedRadioButton);
        marriedRadioButton.setForeground(new java.awt.Color(209, 246, 251));
        marriedRadioButton.setText("Married");
        AddUndergraduate.add(marriedRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 90, 30));

        nameLabel22.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        nameLabel22.setForeground(new java.awt.Color(209, 246, 251));
        nameLabel22.setText("Subject - Grade");
        AddUndergraduate.add(nameLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 130, 30));
        AddUndergraduate.add(phoneBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 190, 30));
        AddUndergraduate.add(alSub1Box, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 200, 30));
        AddUndergraduate.add(alSub2Box, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 200, 30));

        alResultLabel3.setForeground(new java.awt.Color(209, 246, 251));
        alResultLabel3.setText("A/L Result");
        AddUndergraduate.add(alResultLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, 30));
        AddUndergraduate.add(emailBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 200, 30));

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        AddUndergraduate.add(nextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 580, 100, 40));

        nameLabel23.setForeground(new java.awt.Color(209, 246, 251));
        nameLabel23.setText("Gender");
        AddUndergraduate.add(nameLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        dobLabel5.setForeground(new java.awt.Color(209, 246, 251));
        dobLabel5.setText("Date of Birth");
        AddUndergraduate.add(dobLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));
        AddUndergraduate.add(nicBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 210, 30));

        nameLabel24.setForeground(new java.awt.Color(209, 246, 251));
        nameLabel24.setText("Civil Status");
        AddUndergraduate.add(nameLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(209, 246, 251));
        jLabel15.setText("Add Undergraduate Student");
        AddUndergraduate.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 400, 30));

        RightPanel.add(AddUndergraduate, "card2");

        AddUndergraduate2.setBackground(new java.awt.Color(36, 47, 65));
        AddUndergraduate2.setPreferredSize(new java.awt.Dimension(660, 620));
        AddUndergraduate2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        au2enrollButton.setText("Enroll");
        au2enrollButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                au2enrollButtonActionPerformed(evt);
            }
        });
        AddUndergraduate2.add(au2enrollButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 560, -1, 40));

        subject1Label.setForeground(new java.awt.Color(209, 246, 251));
        subject1Label.setText("Select 4 Subjects for Semester 2 :");
        AddUndergraduate2.add(subject1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 300, 40));

        courseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Course", "BM in Accounting and Finance", "BSc in Business Management", "BSc in Software Engineering", "BSc in Information System", "BSc in Civil Engineering", "BSc in Computer Systems Engineering" }));
        courseComboBox.setEnabled(false);
        courseComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseComboBoxActionPerformed(evt);
            }
        });
        AddUndergraduate2.add(courseComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 270, 40));

        intakeLabel.setForeground(new java.awt.Color(209, 246, 251));
        intakeLabel.setText("Intake");
        AddUndergraduate2.add(intakeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 60, 30));

        sem1subLabel.setForeground(new java.awt.Color(209, 246, 251));
        sem1subLabel.setText("Select 4 Subjects for Semester 1:");
        AddUndergraduate2.add(sem1subLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 300, 40));

        sem1sub5.setForeground(new java.awt.Color(209, 246, 251));
        sem1sub5.setEnabled(false);
        AddUndergraduate2.add(sem1sub5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        sem1sub1.setForeground(new java.awt.Color(209, 246, 251));
        sem1sub1.setEnabled(false);
        AddUndergraduate2.add(sem1sub1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        sem1sub2.setForeground(new java.awt.Color(209, 246, 251));
        sem1sub2.setEnabled(false);
        AddUndergraduate2.add(sem1sub2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        sem1sub3.setForeground(new java.awt.Color(209, 246, 251));
        sem1sub3.setEnabled(false);
        AddUndergraduate2.add(sem1sub3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        sem1sub4.setForeground(new java.awt.Color(209, 246, 251));
        sem1sub4.setEnabled(false);
        AddUndergraduate2.add(sem1sub4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        sem2sub1.setForeground(new java.awt.Color(209, 246, 251));
        sem2sub1.setEnabled(false);
        AddUndergraduate2.add(sem2sub1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        sem2sub2.setForeground(new java.awt.Color(209, 246, 251));
        sem2sub2.setEnabled(false);
        AddUndergraduate2.add(sem2sub2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        sem2sub3.setForeground(new java.awt.Color(209, 246, 251));
        sem2sub3.setEnabled(false);
        AddUndergraduate2.add(sem2sub3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        sem2sub4.setForeground(new java.awt.Color(209, 246, 251));
        sem2sub4.setEnabled(false);
        AddUndergraduate2.add(sem2sub4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        sem2sub5.setForeground(new java.awt.Color(209, 246, 251));
        sem2sub5.setEnabled(false);
        AddUndergraduate2.add(sem2sub5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, -1, -1));

        au2backButton1.setText("Back");
        au2backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                au2backButton1ActionPerformed(evt);
            }
        });
        AddUndergraduate2.add(au2backButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, -1, 40));

        courseLabel2.setForeground(new java.awt.Color(209, 246, 251));
        courseLabel2.setText("Course");
        AddUndergraduate2.add(courseLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 60, 30));

        intakeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Intake", "February", "July" }));
        intakeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intakeComboBoxActionPerformed(evt);
            }
        });
        AddUndergraduate2.add(intakeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 140, 40));

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(209, 246, 251));
        jLabel19.setText("Add Undergraduate Student");
        AddUndergraduate2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 400, 30));

        RightPanel.add(AddUndergraduate2, "card3");

        AddPostgraduate.setBackground(new java.awt.Color(36, 47, 65));
        AddPostgraduate.setPreferredSize(new java.awt.Dimension(660, 620));
        AddPostgraduate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        alRankLabel3.setForeground(new java.awt.Color(209, 246, 251));
        alRankLabel3.setText("Institute");
        AddPostgraduate.add(alRankLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, -1, -1));

        nameLabel4.setForeground(new java.awt.Color(209, 246, 251));
        nameLabel4.setText("Name");
        AddPostgraduate.add(nameLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 60, 30));

        dobLabel6.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        dobLabel6.setForeground(new java.awt.Color(209, 246, 251));
        dobLabel6.setText("YYYY-MM-DD");
        AddPostgraduate.add(dobLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        nameLabel25.setForeground(new java.awt.Color(209, 246, 251));
        nameLabel25.setText("Address");
        AddPostgraduate.add(nameLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        nameLabel26.setForeground(new java.awt.Color(209, 246, 251));
        nameLabel26.setText("NIC");
        AddPostgraduate.add(nameLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        nameLabel27.setForeground(new java.awt.Color(209, 246, 251));
        nameLabel27.setText("E-mail");
        AddPostgraduate.add(nameLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 90, 20));

        nameLabel28.setForeground(new java.awt.Color(209, 246, 251));
        nameLabel28.setText("Phone No");
        AddPostgraduate.add(nameLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 90, 20));
        AddPostgraduate.add(nameBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 250, 30));

        genderButtonGroup.add(maleRadioButton1);
        maleRadioButton1.setForeground(new java.awt.Color(209, 246, 251));
        maleRadioButton1.setText("Male");
        maleRadioButton1.setActionCommand("M");
        AddPostgraduate.add(maleRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 80, 30));

        genderButtonGroup.add(femaleRadioButton1);
        femaleRadioButton1.setForeground(new java.awt.Color(209, 246, 251));
        femaleRadioButton1.setText("Female");
        femaleRadioButton1.setActionCommand("F");
        AddPostgraduate.add(femaleRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 90, 30));
        AddPostgraduate.add(dobBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 100, 30));

        addressBox1.setColumns(20);
        addressBox1.setRows(4);
        addressBox1.setPreferredSize(new java.awt.Dimension(200, 50));
        addressBox1.setSize(new java.awt.Dimension(220, 50));
        jScrollPane4.setViewportView(addressBox1);

        AddPostgraduate.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 270, 90));
        AddPostgraduate.add(instituteBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 560, 260, 30));

        civilButtonGroup.add(singleRadioButton1);
        singleRadioButton1.setForeground(new java.awt.Color(209, 246, 251));
        singleRadioButton1.setText("Single");
        AddPostgraduate.add(singleRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 80, 30));

        civilButtonGroup.add(marriedRadioButton1);
        marriedRadioButton1.setForeground(new java.awt.Color(209, 246, 251));
        marriedRadioButton1.setText("Married");
        AddPostgraduate.add(marriedRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 90, 30));
        AddPostgraduate.add(phoneBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 190, 30));
        AddPostgraduate.add(qualificationBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 270, 30));
        AddPostgraduate.add(yearCompletedBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, 160, 30));

        alResultLabel4.setForeground(new java.awt.Color(209, 246, 251));
        alResultLabel4.setText("Year Completed");
        AddPostgraduate.add(alResultLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, 30));
        AddPostgraduate.add(emailBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 200, 30));

        nextButton1.setText("Next");
        nextButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButton1ActionPerformed(evt);
            }
        });
        AddPostgraduate.add(nextButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 580, 100, 40));

        nameLabel30.setForeground(new java.awt.Color(209, 246, 251));
        nameLabel30.setText("Gender");
        AddPostgraduate.add(nameLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        dobLabel7.setForeground(new java.awt.Color(209, 246, 251));
        dobLabel7.setText("Date of Birth");
        AddPostgraduate.add(dobLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));
        AddPostgraduate.add(nicBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 210, 30));

        nameLabel31.setForeground(new java.awt.Color(209, 246, 251));
        nameLabel31.setText("Civil Status");
        AddPostgraduate.add(nameLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        alResultLabel5.setForeground(new java.awt.Color(209, 246, 251));
        alResultLabel5.setText("Qualification");
        AddPostgraduate.add(alResultLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, 30));

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(209, 246, 251));
        jLabel17.setText("Add Postgraduate Student");
        AddPostgraduate.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 400, 30));

        RightPanel.add(AddPostgraduate, "card2");

        AddPostgraduate2.setBackground(new java.awt.Color(36, 47, 65));
        AddPostgraduate2.setPreferredSize(new java.awt.Dimension(660, 620));
        AddPostgraduate2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ap2EnrollButton.setText("Enroll");
        ap2EnrollButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ap2EnrollButtonActionPerformed(evt);
            }
        });
        AddPostgraduate2.add(ap2EnrollButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 560, -1, 40));

        subject1Label1.setForeground(new java.awt.Color(209, 246, 251));
        subject1Label1.setText("Subjects for Semester 2:");
        AddPostgraduate2.add(subject1Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 300, 40));

        courseComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Course", "Master of Business Management", "MSc in Computer Science", "MSc in Construction Project Management" }));
        courseComboBox1.setEnabled(false);
        courseComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseComboBox1ActionPerformed(evt);
            }
        });
        AddPostgraduate2.add(courseComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 270, 40));

        intakeLabel1.setForeground(new java.awt.Color(209, 246, 251));
        intakeLabel1.setText("Intake");
        AddPostgraduate2.add(intakeLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 60, 30));

        sem1subLabel1.setForeground(new java.awt.Color(209, 246, 251));
        sem1subLabel1.setText("Subjects for Semester 1:");
        AddPostgraduate2.add(sem1subLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 300, 40));

        ap2BackButton.setText("Back");
        ap2BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ap2BackButtonActionPerformed(evt);
            }
        });
        AddPostgraduate2.add(ap2BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, -1, 40));

        courseLabel3.setForeground(new java.awt.Color(209, 246, 251));
        courseLabel3.setText("Course");
        AddPostgraduate2.add(courseLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 60, 30));

        intakeComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Intake", "February" }));
        intakeComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intakeComboBox1ActionPerformed(evt);
            }
        });
        AddPostgraduate2.add(intakeComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 140, 40));

        sem2subjects.setBackground(new java.awt.Color(36, 47, 65));
        sem2subjects.setColumns(20);
        sem2subjects.setForeground(new java.awt.Color(209, 246, 251));
        sem2subjects.setRows(5);
        sem2subjects.setBorder(null);
        jScrollPane1.setViewportView(sem2subjects);

        AddPostgraduate2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 320, 130));

        sem1subjects.setBackground(new java.awt.Color(36, 47, 65));
        sem1subjects.setColumns(20);
        sem1subjects.setForeground(new java.awt.Color(209, 246, 251));
        sem1subjects.setRows(5);
        sem1subjects.setBorder(null);
        jScrollPane2.setViewportView(sem1subjects);

        AddPostgraduate2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 320, 130));

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(209, 246, 251));
        jLabel18.setText("Add Postgraduate Student");
        AddPostgraduate2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 400, 30));

        RightPanel.add(AddPostgraduate2, "card3");

        Payment.setBackground(new java.awt.Color(36, 47, 65));
        Payment.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(209, 246, 251));
        jLabel7.setText("Manage Payments");
        Payment.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 190, 30));
        Payment.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 640, -1));

        paymentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        paymentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paymentTableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(paymentTable);

        Payment.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 380, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(209, 246, 251));
        jLabel1.setText("Date");
        Payment.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 90, 30));
        Payment.add(pDateBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 240, 30));

        paymentIdLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        paymentIdLabel.setForeground(new java.awt.Color(209, 246, 251));
        Payment.add(paymentIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 90, 30));
        Payment.add(pSidBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 240, 30));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(209, 246, 251));
        jLabel3.setText("Amount");
        Payment.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 90, 30));
        Payment.add(pAmountBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 240, 30));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(209, 246, 251));
        jLabel4.setText("Student ID");
        Payment.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 90, 30));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(209, 246, 251));
        jLabel5.setText("Payment ID:");
        Payment.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 90, 30));

        pDeleteBtn.setText("DELETE");
        pDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pDeleteBtnActionPerformed(evt);
            }
        });
        Payment.add(pDeleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 180, 40));

        pAddBtn.setText("ADD");
        pAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pAddBtnActionPerformed(evt);
            }
        });
        Payment.add(pAddBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 180, 40));

        RightPanel.add(Payment, "card6");

        SubjectEnrollments.setBackground(new java.awt.Color(36, 47, 65));
        SubjectEnrollments.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(209, 246, 251));
        jLabel8.setText("Undergraduate Subject Enrollment");
        SubjectEnrollments.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 400, 30));
        SubjectEnrollments.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 640, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(209, 246, 251));
        jLabel9.setText("Subject Enrollments");
        SubjectEnrollments.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 400, 30));

        useTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        useTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                useTableMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(useTable);

        SubjectEnrollments.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 290, 220));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(209, 246, 251));
        jLabel10.setText("Subject ID");
        SubjectEnrollments.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 100, 30));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(209, 246, 251));
        jLabel11.setText("Student ID");
        SubjectEnrollments.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 100, 30));
        SubjectEnrollments.add(seSubId, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 230, 30));
        SubjectEnrollments.add(seSid, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 230, 30));

        seDeleteBtn.setText("DELETE");
        seDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seDeleteBtnActionPerformed(evt);
            }
        });
        SubjectEnrollments.add(seDeleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 110, 40));

        seAddBtn.setText("ADD");
        seAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seAddBtnActionPerformed(evt);
            }
        });
        SubjectEnrollments.add(seAddBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 110, 40));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(209, 246, 251));
        jLabel12.setText("Postgraduate Subject Enrollment");
        SubjectEnrollments.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 400, 30));

        pseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        pseTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pseTableMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(pseTable);

        SubjectEnrollments.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 290, 220));
        SubjectEnrollments.add(sepSid, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 230, 30));

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(209, 246, 251));
        jLabel13.setText("Student ID");
        SubjectEnrollments.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 100, 30));
        SubjectEnrollments.add(sepSubId, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 230, 30));

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(209, 246, 251));
        jLabel14.setText("Subject ID");
        SubjectEnrollments.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 100, 30));

        sepAddBtn.setText("ADD");
        sepAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sepAddBtnActionPerformed(evt);
            }
        });
        SubjectEnrollments.add(sepAddBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, 110, 40));

        sepDeleteBtn.setText("DELETE");
        sepDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sepDeleteBtnActionPerformed(evt);
            }
        });
        SubjectEnrollments.add(sepDeleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 530, 110, 40));

        RightPanel.add(SubjectEnrollments, "card7");

        getContentPane().add(RightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 730, 650));

        LeftPanel.setBackground(new java.awt.Color(209, 246, 251));
        LeftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/homeIcon.png"))); // NOI18N
        homeButton.setBorder(null);
        homeButton.setBorderPainted(false);
        homeButton.setContentAreaFilled(false);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        LeftPanel.add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        backButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/backIcon.png"))); // NOI18N
        backButton1.setBorder(null);
        backButton1.setBorderPainted(false);
        backButton1.setContentAreaFilled(false);
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });
        LeftPanel.add(backButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        addPButton.setText("Add Postgraduate");
        addPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPButtonActionPerformed(evt);
            }
        });
        LeftPanel.add(addPButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 150, 50));

        addUButton.setText("Add Undergraduate");
        addUButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUButtonActionPerformed(evt);
            }
        });
        LeftPanel.add(addUButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 150, 50));

        paymentBtn.setText("Payments");
        paymentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentBtnActionPerformed(evt);
            }
        });
        LeftPanel.add(paymentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 150, 50));

        subjectEnrollmentBtn.setText("Subject Enrollments");
        subjectEnrollmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectEnrollmentBtnActionPerformed(evt);
            }
        });
        LeftPanel.add(subjectEnrollmentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 150, 50));

        getContentPane().add(LeftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 650));

        setSize(new java.awt.Dimension(954, 672));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
        
        Main m = new Main();
        m.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_backButton1ActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        
        Main m = new Main();
        m.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_homeButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        
        if(nameBox.getText().isEmpty()||dobBox.getText().isEmpty()||genderButtonGroup.getSelection()==null||nicBox.getText().isEmpty()||addressBox.getText().isEmpty()||phoneBox.getText().isEmpty()||emailBox.getText().isEmpty()||civilButtonGroup.getSelection()==null||alSub1Box.getText().isEmpty()||alSub2Box.getText().isEmpty()||alSub3Box.getText().isEmpty()||alRankBox.getText().isEmpty()) {
            JOptionPane.showConfirmDialog(null, "Please Fill All Fields", "Fields are Empty!", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            RightPanel.removeAll();
            RightPanel.repaint();
            RightPanel.revalidate();
        
            RightPanel.add(AddUndergraduate2);
            RightPanel.repaint();
            RightPanel.revalidate();
        }
        
    }//GEN-LAST:event_nextButtonActionPerformed

    private void au2enrollButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_au2enrollButtonActionPerformed
        
        if(courseComboBox.getSelectedIndex()==0) {
            JOptionPane.showConfirmDialog(null, "Please Select a Intake & a Course", "Not Selected", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
        }
       
        int sem1count = 0;
        int sem2count = 0;
        int intakeIndex = intakeComboBox.getSelectedIndex();
       
        JCheckBox[] checkBoxes = {sem1sub1, sem1sub2, sem1sub3, sem1sub4, sem1sub5, sem2sub1, sem2sub2, sem2sub3, sem2sub4, sem2sub5};
       
      
        for(int i=0; i<5; i++) {
            if(checkBoxes[i].isSelected()) {
                sem1count += 1;
            }
        }
       
        for(int i=5; i<10; i++) {
            if(checkBoxes[i].isSelected()) {
                sem2count += 1;
            }
        }
        
        if(sem1count != 4 && intakeIndex==1) {
            JOptionPane.showConfirmDialog(null, "Please Select 4 Subject for Semester 1", "Invalid Number of Subjects!", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
        }
        else if(sem2count != 4) {
            JOptionPane.showConfirmDialog(null, "Please Select 4 Subject for Semester 2", "Invalid Number of Subjects!", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
        }
        
        else {
          
            String name = nameBox.getText();
            String dob = dobBox.getText();
            char gender = genderButtonGroup.getSelection().getActionCommand().charAt(0);
            String nic = nicBox.getText();
            String address = addressBox.getText();
            String phone = phoneBox.getText();
            String email = emailBox.getText();
            
            singleRadioButton.setActionCommand("Single");
            marriedRadioButton.setActionCommand("Married");
            String status = civilButtonGroup.getSelection().getActionCommand();
            
            String result = alSub1Box.getText()+", "+alSub2Box.getText()+", "+alSub3Box.getText();
            int rank = Integer.parseInt(alRankBox.getText());
            
            String course = (String) courseComboBox.getSelectedItem();
            String intake = (String) intakeComboBox.getSelectedItem();
            
            String sem1[] = new String[4];
            String sem2[] = new String[4];
            int sem1Int = 0;
            int sem2Int = 0;
            
            for(int i=0; i<5; i++) {
                if(checkBoxes[i].isSelected()) {
                    sem1[sem1Int] = checkBoxes[i].getActionCommand();
                    sem1Int += 1;
                }
            }
       
            for(int i=5; i<10; i++) {
                if(checkBoxes[i].isSelected()) {
                    sem2[sem2Int] = checkBoxes[i].getActionCommand();
                    sem2Int += 1;
                }
            }
            
            
            UndergradStu us = new UndergradStu(name, dob, gender, nic, status, phone, email, address, result, rank);
            
            if(intakeIndex==1) {
                us.enroll(course, sem1, sem2, intake);
            }
            else {
                us.enroll(course, sem2, intake);
            }
            
            Payment p = new Payment(us);
            p.setVisible(true);
            this.setVisible(false);
            
        }
        
    }//GEN-LAST:event_au2enrollButtonActionPerformed

    private void courseComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseComboBoxActionPerformed
        
            int intake = intakeComboBox.getSelectedIndex();
            int index = courseComboBox.getSelectedIndex();
        
            if(index!=0 && intake==1) {
                sem1sub1.setSelected(false);
                sem1sub2.setSelected(false);
                sem1sub3.setSelected(false);
                sem1sub4.setSelected(false);
                sem1sub5.setSelected(false);
                sem2sub1.setSelected(false);
                sem2sub2.setSelected(false);
                sem2sub3.setSelected(false);
                sem2sub4.setSelected(false);
                sem2sub5.setSelected(false);
            
                sem1sub1.setEnabled(true);
                sem1sub2.setEnabled(true);
                sem1sub3.setEnabled(true);
                sem1sub4.setEnabled(true);
                sem1sub5.setEnabled(true);
                sem2sub1.setEnabled(true);
                sem2sub2.setEnabled(true);
                sem2sub3.setEnabled(true);
                sem2sub4.setEnabled(true);
                sem2sub5.setEnabled(true);
            }
            if(index!=0 && intake==2) {
                sem1sub1.setSelected(false);
                sem1sub2.setSelected(false);
                sem1sub3.setSelected(false);
                sem1sub4.setSelected(false);
                sem1sub5.setSelected(false);
                sem2sub1.setSelected(false);
                sem2sub2.setSelected(false);
                sem2sub3.setSelected(false);
                sem2sub4.setSelected(false);
                sem2sub5.setSelected(false);
                
                sem1sub1.setEnabled(false); sem1sub1.setText("");
                sem1sub2.setEnabled(false); sem1sub2.setText("");
                sem1sub3.setEnabled(false); sem1sub3.setText("");
                sem1sub4.setEnabled(false); sem1sub4.setText("");
                sem1sub5.setEnabled(false); sem1sub5.setText("");
                sem2sub1.setEnabled(true);
                sem2sub2.setEnabled(true);
                sem2sub3.setEnabled(true);
                sem2sub4.setEnabled(true);
                sem2sub5.setEnabled(true);
            }
           
        
            if(index==0) {
                sem1sub1.setSelected(false);
                sem1sub2.setSelected(false);
                sem1sub3.setSelected(false);
                sem1sub4.setSelected(false);
                sem1sub5.setSelected(false);
                sem2sub1.setSelected(false);
                sem2sub2.setSelected(false);
                sem2sub3.setSelected(false);
                sem2sub4.setSelected(false);
                sem2sub5.setSelected(false);
            
                sem1sub1.setEnabled(false); sem1sub1.setText("");
                sem1sub2.setEnabled(false); sem1sub2.setText("");
                sem1sub3.setEnabled(false); sem1sub3.setText("");
                sem1sub4.setEnabled(false); sem1sub4.setText("");
                sem1sub5.setEnabled(false); sem1sub5.setText("");
                sem2sub1.setEnabled(false); sem2sub1.setText("");
                sem2sub2.setEnabled(false); sem2sub2.setText("");
                sem2sub3.setEnabled(false); sem2sub3.setText("");
                sem2sub4.setEnabled(false); sem2sub4.setText("");
                sem2sub5.setEnabled(false); sem2sub5.setText("");
            }
        
            if(index==1) {
                if(intake==1) {
                    sem1sub1.setSelected(false);
                    sem1sub2.setSelected(false);
                    sem1sub3.setSelected(false);
                    sem1sub4.setSelected(false);
                    sem1sub5.setSelected(false);
                    sem2sub1.setSelected(false);
                    sem2sub2.setSelected(false);
                    sem2sub3.setSelected(false);
                    sem2sub4.setSelected(false);
                    sem2sub5.setSelected(false);

                    sem1sub1.setText("Business English");
                    sem1sub1.setActionCommand("BAF1104");
                    sem1sub2.setText("Micro Economics");
                    sem1sub2.setActionCommand("BAF1105");
                    sem1sub3.setText("Business Science");
                    sem1sub3.setActionCommand("BAF1106");
                    sem1sub4.setText("Business Mathematics and Statistics");
                    sem1sub4.setActionCommand("BAF1107");
                    sem1sub5.setText("Introduction to Management Accounting");
                    sem1sub5.setActionCommand("BAF1108");
                    sem2sub1.setText("Business Mathematics and Statistics II");
                    sem2sub1.setActionCommand("BAF1204");
                    sem2sub2.setText("Critical Enabling and Skills Training");
                    sem2sub2.setActionCommand("BAF1205");
                    sem2sub3.setText("Historical and Cultural Influence");
                    sem2sub3.setActionCommand("BAF1206");
                    sem2sub4.setText("Business Psychology");
                    sem2sub4.setActionCommand("BAF1207");
                    sem2sub5.setText("Digital Communication I");
                    sem2sub5.setActionCommand("BAF1208");
                }
                else if(intake==2) {
                    sem1sub1.setSelected(false);
                    sem1sub2.setSelected(false);
                    sem1sub3.setSelected(false);
                    sem1sub4.setSelected(false);
                    sem1sub5.setSelected(false);
                    sem2sub1.setSelected(false);
                    sem2sub2.setSelected(false);
                    sem2sub3.setSelected(false);
                    sem2sub4.setSelected(false);
                    sem2sub5.setSelected(false);
                    
                    sem2sub1.setText("Business Mathematics and Statistics II");
                    sem2sub1.setActionCommand("BAF1204");
                    sem2sub2.setText("Critical Enabling and Skills Training");
                    sem2sub2.setActionCommand("BAF1205");
                    sem2sub3.setText("Historical and Cultural Influence");
                    sem2sub3.setActionCommand("BAF1206");
                    sem2sub4.setText("Business Psychology");
                    sem2sub4.setActionCommand("BAF1207");
                    sem2sub5.setText("Digital Communication I");
                    sem2sub5.setActionCommand("BAF1208");
                }
            }
            else if(index==2) {
                if(intake==1) {
                    sem1sub1.setSelected(false);
                    sem1sub2.setSelected(false);
                    sem1sub3.setSelected(false);
                    sem1sub4.setSelected(false);
                    sem1sub5.setSelected(false);
                    sem2sub1.setSelected(false);
                    sem2sub2.setSelected(false);
                    sem2sub3.setSelected(false);
                    sem2sub4.setSelected(false);
                    sem2sub5.setSelected(false);

                    sem1sub1.setText("Business English");
                    sem1sub1.setActionCommand("BBM1104");
                    sem1sub2.setText("Economics for Managers");
                    sem1sub2.setActionCommand("BBM1105");
                    sem1sub3.setText("Business Science");
                    sem1sub3.setActionCommand("BBM1106");
                    sem1sub4.setText("Business Mathematics and Statistics");
                    sem1sub4.setActionCommand("BBM1107");
                    sem1sub5.setText("Introduction to Management Accounting");
                    sem1sub5.setActionCommand("BBM1108");
                    sem2sub1.setText("Introduction to Project Management");
                    sem2sub1.setActionCommand("BBM1204");
                    sem2sub2.setText("Critical Enabling and Skills Training");
                    sem2sub2.setActionCommand("BBM1205");
                    sem2sub3.setText("Digital Communication I");
                    sem2sub3.setActionCommand("BBM1206");
                    sem2sub4.setText("Business Psychology");
                    sem2sub4.setActionCommand("BBM1207");
                    sem2sub5.setText("Project Handling");
                    sem2sub5.setActionCommand("BBM1208");
                }
                else if(intake==2) {
                    sem1sub1.setSelected(false);
                    sem1sub2.setSelected(false);
                    sem1sub3.setSelected(false);
                    sem1sub4.setSelected(false);
                    sem1sub5.setSelected(false);
                    sem2sub1.setSelected(false);
                    sem2sub2.setSelected(false);
                    sem2sub3.setSelected(false);
                    sem2sub4.setSelected(false);
                    sem2sub5.setSelected(false);
                    
                    sem2sub1.setText("Introduction to Project Management");
                    sem2sub1.setActionCommand("BBM1204");
                    sem2sub2.setText("Critical Enabling and Skills Training");
                    sem2sub2.setActionCommand("BBM1205");
                    sem2sub3.setText("Digital Communication I");
                    sem2sub3.setActionCommand("BBM1206");
                    sem2sub4.setText("Business Psychology");
                    sem2sub4.setActionCommand("BBM1207");
                    sem2sub5.setText("Project Handling");
                    sem2sub5.setActionCommand("BBM1208");
                }
            }
            else if(index==3) {
                if(intake==1) {
                    sem1sub1.setSelected(false);
                    sem1sub2.setSelected(false);
                    sem1sub3.setSelected(false);
                    sem1sub4.setSelected(false);
                    sem1sub5.setSelected(false);
                    sem2sub1.setSelected(false);
                    sem2sub2.setSelected(false);
                    sem2sub3.setSelected(false);
                    sem2sub4.setSelected(false);
                    sem2sub5.setSelected(false);

                    sem1sub1.setText("Professional Development");
                    sem1sub1.setActionCommand("BSW1104");
                    sem1sub2.setText("Data Communication and Networks");
                    sem1sub2.setActionCommand("BSW1105");
                    sem1sub3.setText("Introduction to Computer Systems");
                    sem1sub3.setActionCommand("BSW1106");
                    sem1sub4.setText("Discrete Mathematics I");
                    sem1sub4.setActionCommand("BSW1107");
                    sem1sub5.setText("Programming in Python");
                    sem1sub5.setActionCommand("BSW1108");
                    sem2sub1.setText("Database Management System");
                    sem2sub1.setActionCommand("BSW1204");
                    sem2sub2.setText("Web-based Application Development");
                    sem2sub2.setActionCommand("BSW1205");
                    sem2sub3.setText("Laboratory I");
                    sem2sub3.setActionCommand("BSW1206");
                    sem2sub4.setText("Discrete Mathematics II");
                    sem2sub4.setActionCommand("BSW1207");
                    sem2sub5.setText("Programming in Scala ");
                    sem2sub5.setActionCommand("BSW1208");
                }
                else if(intake==2) {
                    sem1sub1.setSelected(false);
                    sem1sub2.setSelected(false);
                    sem1sub3.setSelected(false);
                    sem1sub4.setSelected(false);
                    sem1sub5.setSelected(false);
                    sem2sub1.setSelected(false);
                    sem2sub2.setSelected(false);
                    sem2sub3.setSelected(false);
                    sem2sub4.setSelected(false);
                    sem2sub5.setSelected(false);
                    
                    sem2sub1.setText("Database Management System");
                    sem2sub1.setActionCommand("BSW1204");
                    sem2sub2.setText("Web-based Application Development");
                    sem2sub2.setActionCommand("BSW1205");
                    sem2sub3.setText("Laboratory I");
                    sem2sub3.setActionCommand("BSW1206");
                    sem2sub4.setText("Discrete Mathematics II");
                    sem2sub4.setActionCommand("BSW1207");
                    sem2sub5.setText("Programming in Scala ");
                    sem2sub5.setActionCommand("BSW1208");
                }
            }
            else if(index==4) {
                if(intake==1) {
                    sem1sub1.setSelected(false);
                    sem1sub2.setSelected(false);
                    sem1sub3.setSelected(false);
                    sem1sub4.setSelected(false);
                    sem1sub5.setSelected(false);
                    sem2sub1.setSelected(false);
                    sem2sub2.setSelected(false);
                    sem2sub3.setSelected(false);
                    sem2sub4.setSelected(false);
                    sem2sub5.setSelected(false);

                    sem1sub1.setText("Computer Organization");
                    sem1sub1.setActionCommand("BIS1104");
                    sem1sub2.setText("OOP with C++");
                    sem1sub2.setActionCommand("BIS1105");
                    sem1sub3.setText("Business Information System");
                    sem1sub3.setActionCommand("BIS1106");
                    sem1sub4.setText("Database Management System");
                    sem1sub4.setActionCommand("BIS1107");
                    sem1sub5.setText("Laboratory I");
                    sem1sub5.setActionCommand("BIS1108");
                    sem2sub1.setText("Internet Programming");
                    sem2sub1.setActionCommand("BIS1204");
                    sem2sub2.setText("System Analysis and Design");
                    sem2sub2.setActionCommand("BIS1205");
                    sem2sub3.setText("Software Skills");
                    sem2sub3.setActionCommand("BIS1206");
                    sem2sub4.setText("System Design Project ");
                    sem2sub4.setActionCommand("BIS1207");
                    sem2sub5.setText("Laboratory II");
                    sem2sub5.setActionCommand("BIS1208");
                }
                else if(intake==2) {
                    sem1sub1.setSelected(false);
                    sem1sub2.setSelected(false);
                    sem1sub3.setSelected(false);
                    sem1sub4.setSelected(false);
                    sem1sub5.setSelected(false);
                    sem2sub1.setSelected(false);
                    sem2sub2.setSelected(false);
                    sem2sub3.setSelected(false);
                    sem2sub4.setSelected(false);
                    sem2sub5.setSelected(false);
                    
                    sem2sub1.setText("Internet Programming");
                    sem2sub1.setActionCommand("BIS1204");
                    sem2sub2.setText("System Analysis and Design");
                    sem2sub2.setActionCommand("BIS1205");
                    sem2sub3.setText("Software Skills");
                    sem2sub3.setActionCommand("BIS1206");
                    sem2sub4.setText("System Design Project ");
                    sem2sub4.setActionCommand("BIS1207");
                    sem2sub5.setText("Laboratory II");
                    sem2sub5.setActionCommand("BIS1208");
                }
            }
            else if(index==5) {
                if(intake==1) {
                    sem1sub1.setSelected(false);
                    sem1sub2.setSelected(false);
                    sem1sub3.setSelected(false);
                    sem1sub4.setSelected(false);
                    sem1sub5.setSelected(false);
                    sem2sub1.setSelected(false);
                    sem2sub2.setSelected(false);
                    sem2sub3.setSelected(false);
                    sem2sub4.setSelected(false);
                    sem2sub5.setSelected(false);

                    sem1sub1.setText("Engineering Mathematics I");
                    sem1sub1.setActionCommand("BCE1104");
                    sem1sub2.setText("Engllish Language Skills I");
                    sem1sub2.setActionCommand("BCE1105");
                    sem1sub3.setText("Introduction to Renewable Energy");
                    sem1sub3.setActionCommand("BCE1106");
                    sem1sub4.setText("Introduction to Sustainable Engineering");
                    sem1sub4.setActionCommand("BCE1107");
                    sem1sub5.setText("Introduction to Mechanics and Fluids");
                    sem1sub5.setActionCommand("BCE1108");
                    sem2sub1.setText("Engineering Mathematics II");
                    sem2sub1.setActionCommand("BCE1204");
                    sem2sub2.setText("Engineering Programming");
                    sem2sub2.setActionCommand("BCE1205");
                    sem2sub3.setText("English Language Skills II");
                    sem2sub3.setActionCommand("BCE1206");
                    sem2sub4.setText("Engineering Architectures");
                    sem2sub4.setActionCommand("BCE1207");
                    sem2sub5.setText("Characteristics of Fluids");
                    sem2sub5.setActionCommand("BCE1208");
                }
                else if(intake==2) {
                    sem1sub1.setSelected(false);
                    sem1sub2.setSelected(false);
                    sem1sub3.setSelected(false);
                    sem1sub4.setSelected(false);
                    sem1sub5.setSelected(false);
                    sem2sub1.setSelected(false);
                    sem2sub2.setSelected(false);
                    sem2sub3.setSelected(false);
                    sem2sub4.setSelected(false);
                    sem2sub5.setSelected(false);
                    
                    sem2sub1.setText("Engineering Mathematics II");
                    sem2sub1.setActionCommand("BCE1204");
                    sem2sub2.setText("Engineering Programming");
                    sem2sub2.setActionCommand("BCE1205");
                    sem2sub3.setText("English Language Skills II");
                    sem2sub3.setActionCommand("BCE1206");
                    sem2sub4.setText("Engineering Architectures");
                    sem2sub4.setActionCommand("BCE1207");
                    sem2sub5.setText("Characteristics of Fluids");
                    sem2sub5.setActionCommand("BCE1208");
                }
            }
            else if(index==6) {
                if(intake==1) {
                    sem1sub1.setSelected(false);
                    sem1sub2.setSelected(false);
                    sem1sub3.setSelected(false);
                    sem1sub4.setSelected(false);
                    sem1sub5.setSelected(false);
                    sem2sub1.setSelected(false);
                    sem2sub2.setSelected(false);
                    sem2sub3.setSelected(false);
                    sem2sub4.setSelected(false);
                    sem2sub5.setSelected(false);

                    sem1sub1.setText("Fundamentals of Electrical Engineering");
                    sem1sub1.setActionCommand("BSE1103");
                    sem1sub2.setText("Electronics I");
                    sem1sub2.setActionCommand("BSE1104");
                    sem1sub3.setText("Computer Aided Design");
                    sem1sub3.setActionCommand("BSE1105");
                    sem1sub4.setText("Engineering Mechanics");
                    sem1sub4.setActionCommand("BSE1106");
                    sem1sub5.setText("Engineering Design and Processes");
                    sem1sub5.setActionCommand("BSE1107");
                    sem2sub1.setText("Engineering Materials");
                    sem2sub1.setActionCommand("BSE1203");
                    sem2sub2.setText("Computer Architecture and Organization");
                    sem2sub2.setActionCommand("BSE1204");
                    sem2sub3.setText("Introductory Mechanics and Fluids");
                    sem2sub3.setActionCommand("BSE1205");
                    sem2sub4.setText("Engineering Skills Development");
                    sem2sub4.setActionCommand("BSE1206");
                    sem2sub5.setText("Engineering Principles and Communication");
                    sem2sub5.setActionCommand("BSE1207");
                }
                else if(intake==2) {
                    sem1sub1.setSelected(false);
                    sem1sub2.setSelected(false);
                    sem1sub3.setSelected(false);
                    sem1sub4.setSelected(false);
                    sem1sub5.setSelected(false);
                    sem2sub1.setSelected(false);
                    sem2sub2.setSelected(false);
                    sem2sub3.setSelected(false);
                    sem2sub4.setSelected(false);
                    sem2sub5.setSelected(false);
                    
                    sem2sub1.setText("Engineering Materials");
                    sem2sub1.setActionCommand("BSE1203");
                    sem2sub2.setText("Computer Architecture and Organization");
                    sem2sub2.setActionCommand("BSE1204");
                    sem2sub3.setText("Introductory Mechanics and Fluids");
                    sem2sub3.setActionCommand("BSE1205");
                    sem2sub4.setText("Engineering Skills Development");
                    sem2sub4.setActionCommand("BSE1206");
                    sem2sub5.setText("Engineering Principles and Communication");
                    sem2sub5.setActionCommand("BSE1207");
                }
            }
        
    }//GEN-LAST:event_courseComboBoxActionPerformed

    private void au2backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_au2backButton1ActionPerformed
        
        RightPanel.removeAll();
        RightPanel.repaint();
        RightPanel.revalidate();
        
        RightPanel.add(AddUndergraduate);
        RightPanel.repaint();
        RightPanel.revalidate();
        
    }//GEN-LAST:event_au2backButton1ActionPerformed

    private void intakeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intakeComboBoxActionPerformed
        
        if(intakeComboBox.getSelectedIndex()!=0) {
            courseComboBox.setEnabled(true);
        }
        if(intakeComboBox.getSelectedIndex()==0) {
            sem1subLabel.setText("Select 4 Subjects for Semester 1");
        }
        else if(intakeComboBox.getSelectedIndex()==1) {
            sem1subLabel.setText("Select 4 Subjects for Semester 1");
        }
        else if(intakeComboBox.getSelectedIndex()==2) {
            sem1subLabel.setText("You can select subjects for Semester 2 only");
        }
        
    }//GEN-LAST:event_intakeComboBoxActionPerformed

    private void nextButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButton1ActionPerformed
        
        if(nameBox1.getText().isEmpty()||dobBox1.getText().isEmpty()||genderButtonGroup.getSelection()==null||nicBox1.getText().isEmpty()||addressBox1.getText().isEmpty()||phoneBox1.getText().isEmpty()||emailBox1.getText().isEmpty()||civilButtonGroup.getSelection()==null||qualificationBox.getText().isEmpty()||yearCompletedBox.getText().isEmpty()||instituteBox.getText().isEmpty()) {
            JOptionPane.showConfirmDialog(null, "Please Fill All Fields", "Fields are Empty!", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            RightPanel.removeAll();
            RightPanel.repaint();
            RightPanel.revalidate();
        
            RightPanel.add(AddPostgraduate2);
            RightPanel.repaint();
            RightPanel.revalidate();
        }
        
    }//GEN-LAST:event_nextButton1ActionPerformed

    private void ap2EnrollButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ap2EnrollButtonActionPerformed
        
        if(courseComboBox1.getSelectedIndex()==0) {
            
            JOptionPane.showConfirmDialog(null, "Please Select a Intake & a Course", "Not Selected", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
        
        }
        
        else {
            
            String name = nameBox1.getText();
            String dob = dobBox1.getText();
            char gender = genderButtonGroup.getSelection().getActionCommand().charAt(0);
            String nic = nicBox1.getText();
            String address = addressBox1.getText();
            String phone = phoneBox1.getText();
            String email = emailBox1.getText();
            
            singleRadioButton1.setActionCommand("Single");
            marriedRadioButton1.setActionCommand("Married");
            String status = civilButtonGroup.getSelection().getActionCommand();
            
            String qualification = qualificationBox.getText();
            int yearCompleted = Integer.parseInt(yearCompletedBox.getText());
            String institute = instituteBox.getText();
            
            String course = (String) courseComboBox1.getSelectedItem();
            String intake = (String) intakeComboBox1.getSelectedItem();
            
            PostgradStu ps = new PostgradStu(name, dob, gender, nic, status, phone, email, address, qualification, yearCompleted, institute);
            
            ps.enroll(course, intake);
            
            Payment p = new Payment(ps);
            p.setVisible(true);
            this.setVisible(false);
            
        }
        
    }//GEN-LAST:event_ap2EnrollButtonActionPerformed

    private void courseComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseComboBox1ActionPerformed
        
        int index = courseComboBox1.getSelectedIndex();
        
        if(index==0) {
            sem1subjects.setText("");
            sem2subjects.setText("");
        }
        if(index==1) {
            sem1subjects.setText("\nBusiness Economics\nEnterprise Management\nQuantitative Methods for Management\nAccounting for Decision Makers\nBusiness Communication\nMarketing Management");
            sem2subjects.setText("\nManagement Finance\nOrganizational Behavior\nLegal Aspects of Managers\nInternational Business Management\nManaging Information System\nBusiness Ethics and Sustainability");
        }
        if(index==2) {
            sem1subjects.setText("\nAdvanced Algorithms\nAdvanced Software Engineering\nAdvanced Database System\nPrinciples of Programming Languages");
            sem2subjects.setText("\nInformation System Security\nAdvanced Concepts in Data Communication Networks\nData Analytics and Machine Learning\nTheoretical Computing");
        }
        if(index==3) {
            sem1subjects.setText("\nProject Management I\nProject Management II\nManagement Information Systems\nConstruction and Industrial Law");
            sem2subjects.setText("\nProcurement and Conditions of Contracts\nHuman Resource Management\nConstruction Project Management Application\nFinancial Management");
        }
        
    }//GEN-LAST:event_courseComboBox1ActionPerformed

    private void ap2BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ap2BackButtonActionPerformed
        
        RightPanel.removeAll();
        RightPanel.repaint();
        RightPanel.revalidate();
        
        RightPanel.add(AddPostgraduate);
        RightPanel.repaint();
        RightPanel.revalidate();
        
    }//GEN-LAST:event_ap2BackButtonActionPerformed

    private void intakeComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intakeComboBox1ActionPerformed
        
        if(intakeComboBox1.getSelectedIndex()!=0) {
            courseComboBox1.setEnabled(true);
        }
        
    }//GEN-LAST:event_intakeComboBox1ActionPerformed

    private void addPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPButtonActionPerformed
        
        RightPanel.removeAll();
        RightPanel.repaint();
        RightPanel.revalidate();
        
        RightPanel.add(AddPostgraduate);
        RightPanel.repaint();
        RightPanel.revalidate();
        
    }//GEN-LAST:event_addPButtonActionPerformed

    private void addUButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUButtonActionPerformed
        
        RightPanel.removeAll();
        RightPanel.repaint();
        RightPanel.revalidate();
        
        RightPanel.add(AddUndergraduate);
        RightPanel.repaint();
        RightPanel.revalidate();
        
    }//GEN-LAST:event_addUButtonActionPerformed

    private void paymentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentBtnActionPerformed
        
        RightPanel.removeAll();
        RightPanel.repaint();
        RightPanel.revalidate();
        
        RightPanel.add(Payment);
        RightPanel.repaint();
        RightPanel.revalidate();
        
    }//GEN-LAST:event_paymentBtnActionPerformed

    private void paymentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentTableMouseClicked
        
        int r = paymentTable.getSelectedRow();
        
        String paymentId = paymentTable.getValueAt(r, 0).toString();
        String studentId = paymentTable.getValueAt(r, 1).toString();
        String payedAmount = paymentTable.getValueAt(r, 2).toString();
        String payedDate = paymentTable.getValueAt(r, 3).toString();
        
        paymentIdLabel.setText(paymentId);
        pSidBox.setText(studentId);
        pAmountBox.setText(payedAmount);
        pDateBox.setText(payedDate);
        
    }//GEN-LAST:event_paymentTableMouseClicked

    private void pAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pAddBtnActionPerformed
        
        if(pSidBox.getText().isEmpty() || pAmountBox.getText().isEmpty() || pDateBox.getText().isEmpty()) {
            
            JOptionPane.showConfirmDialog(null, "Please Fill All Fields", "Fields are Empty!", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
        }
        
        else {
            
            String sid = pSidBox.getText();
            Double amount = Double.parseDouble(pAmountBox.getText());
            String date = pDateBox.getText();
            
            StuPayments p = new StuPayments(sid, amount, date);
            p.add();
            
            paymentIdLabel.setText("");
            pSidBox.setText("");
            pAmountBox.setText("");
            pDateBox.setText("");
            tableLoadPayment();
            
        }
        
    }//GEN-LAST:event_pAddBtnActionPerformed

    private void pDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pDeleteBtnActionPerformed
        
        int x = JOptionPane.showConfirmDialog(null, "Do you want to delete this record?");
        
        if(x==0) {
        
            String paymentId = paymentIdLabel.getText();
            StuPayments p = new StuPayments(paymentId);
            p.delete();
           
            tableLoadPayment();

            paymentIdLabel.setText("");
            pSidBox.setText("");
            pAmountBox.setText("");
            pDateBox.setText("");
        
        }
        
    }//GEN-LAST:event_pDeleteBtnActionPerformed

    private void subjectEnrollmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectEnrollmentBtnActionPerformed
        
        RightPanel.removeAll();
        RightPanel.repaint();
        RightPanel.revalidate();
        
        RightPanel.add(SubjectEnrollments);
        RightPanel.repaint();
        RightPanel.revalidate();
        
    }//GEN-LAST:event_subjectEnrollmentBtnActionPerformed

    private void useTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_useTableMouseClicked
        
        int r = useTable.getSelectedRow();
        
        String sId = useTable.getValueAt(r, 0).toString();
        String subId = useTable.getValueAt(r, 1).toString();
        
        seSid.setText(sId);
        seSubId.setText(subId);
        
    }//GEN-LAST:event_useTableMouseClicked

    private void pseTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pseTableMouseClicked
        
        int r = pseTable.getSelectedRow();
        
        String sId = pseTable.getValueAt(r, 0).toString();
        String subId = pseTable.getValueAt(r, 1).toString();
        
        sepSid.setText(sId);
        sepSubId.setText(subId);
        
    }//GEN-LAST:event_pseTableMouseClicked

    private void seAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seAddBtnActionPerformed
        
        if(seSid.getText().isEmpty() || seSubId.getText().isEmpty()) {
            
            JOptionPane.showConfirmDialog(null, "Please Fill All Fields", "Fields are Empty!", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
            
        }
        
        else {
            
            String sid = seSid.getText();
            String subId = seSubId.getText();
            
            StudentSubjects ss = new StudentSubjects(sid, subId);
            ss.add();
            
            seSid.setText("");
            seSubId.setText("");
            
            tableLoadUndergradSub();
            
        }
        
    }//GEN-LAST:event_seAddBtnActionPerformed

    private void seDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seDeleteBtnActionPerformed
        
        int x = JOptionPane.showConfirmDialog(null, "Do you want to delete this record?");
        
        if(x==0) {
        
            String sId = seSid.getText();
            String subId = seSubId.getText();
            
            StudentSubjects ss = new StudentSubjects(sId, subId);
            ss.delete();
           
            tableLoadUndergradSub();

            seSid.setText("");
            seSubId.setText("");
        
        }
        
    }//GEN-LAST:event_seDeleteBtnActionPerformed

    private void sepAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sepAddBtnActionPerformed
        
        if(sepSid.getText().isEmpty() || sepSubId.getText().isEmpty()) {
            
            JOptionPane.showConfirmDialog(null, "Please Fill All Fields", "Fields are Empty!", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
            
        }
        
        else {
            
            String sid = sepSid.getText();
            String subId = sepSubId.getText();
            
            StudentSubjects ss = new StudentSubjects(sid, subId);
            ss.addPost();
            
            sepSid.setText("");
            sepSubId.setText("");
            
            tableLoadPostgradSub();
            
        }
        
    }//GEN-LAST:event_sepAddBtnActionPerformed

    private void sepDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sepDeleteBtnActionPerformed
        
        int x = JOptionPane.showConfirmDialog(null, "Do you want to delete this record?");
        
        if(x==0) {
        
            String sId = sepSid.getText();
            String subId = sepSubId.getText();
            
            StudentSubjects ss = new StudentSubjects(sId, subId);
            ss.deletePost();
           
            tableLoadPostgradSub();

            sepSid.setText("");
            sepSubId.setText("");
        
        }
        
    }//GEN-LAST:event_sepDeleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentEnrollment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentEnrollment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentEnrollment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentEnrollment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentEnrollment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddPostgraduate;
    private javax.swing.JPanel AddPostgraduate2;
    private javax.swing.JPanel AddUndergraduate;
    private javax.swing.JPanel AddUndergraduate2;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JPanel Payment;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JPanel SubjectEnrollments;
    private javax.swing.JButton addPButton;
    private javax.swing.JButton addUButton;
    private javax.swing.JTextArea addressBox;
    private javax.swing.JTextArea addressBox1;
    private javax.swing.JTextField alRankBox;
    private javax.swing.JLabel alRankLabel2;
    private javax.swing.JLabel alRankLabel3;
    private javax.swing.JLabel alResultLabel3;
    private javax.swing.JLabel alResultLabel4;
    private javax.swing.JLabel alResultLabel5;
    private javax.swing.JTextField alSub1Box;
    private javax.swing.JTextField alSub2Box;
    private javax.swing.JTextField alSub3Box;
    private javax.swing.JButton ap2BackButton;
    private javax.swing.JButton ap2EnrollButton;
    private javax.swing.JButton au2backButton1;
    private javax.swing.JButton au2enrollButton;
    private javax.swing.JButton backButton1;
    private javax.swing.ButtonGroup civilButtonGroup;
    private javax.swing.JComboBox<String> courseComboBox;
    private javax.swing.JComboBox<String> courseComboBox1;
    private javax.swing.JLabel courseLabel2;
    private javax.swing.JLabel courseLabel3;
    private javax.swing.JTextField dobBox;
    private javax.swing.JTextField dobBox1;
    private javax.swing.JLabel dobLabel4;
    private javax.swing.JLabel dobLabel5;
    private javax.swing.JLabel dobLabel6;
    private javax.swing.JLabel dobLabel7;
    private javax.swing.JTextField emailBox;
    private javax.swing.JTextField emailBox1;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.JRadioButton femaleRadioButton1;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JButton homeButton;
    private javax.swing.JTextField instituteBox;
    private javax.swing.JComboBox<String> intakeComboBox;
    private javax.swing.JComboBox<String> intakeComboBox1;
    private javax.swing.JLabel intakeLabel;
    private javax.swing.JLabel intakeLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JRadioButton maleRadioButton1;
    private javax.swing.JRadioButton marriedRadioButton;
    private javax.swing.JRadioButton marriedRadioButton1;
    private javax.swing.JTextField nameBox;
    private javax.swing.JTextField nameBox1;
    private javax.swing.JLabel nameLabel18;
    private javax.swing.JLabel nameLabel19;
    private javax.swing.JLabel nameLabel20;
    private javax.swing.JLabel nameLabel21;
    private javax.swing.JLabel nameLabel22;
    private javax.swing.JLabel nameLabel23;
    private javax.swing.JLabel nameLabel24;
    private javax.swing.JLabel nameLabel25;
    private javax.swing.JLabel nameLabel26;
    private javax.swing.JLabel nameLabel27;
    private javax.swing.JLabel nameLabel28;
    private javax.swing.JLabel nameLabel3;
    private javax.swing.JLabel nameLabel30;
    private javax.swing.JLabel nameLabel31;
    private javax.swing.JLabel nameLabel4;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton nextButton1;
    private javax.swing.JTextField nicBox;
    private javax.swing.JTextField nicBox1;
    private javax.swing.JButton pAddBtn;
    private javax.swing.JTextField pAmountBox;
    private javax.swing.JTextField pDateBox;
    private javax.swing.JButton pDeleteBtn;
    private javax.swing.JTextField pSidBox;
    private javax.swing.JButton paymentBtn;
    private javax.swing.JLabel paymentIdLabel;
    private javax.swing.JTable paymentTable;
    private javax.swing.JTextField phoneBox;
    private javax.swing.JTextField phoneBox1;
    private javax.swing.JTable pseTable;
    private javax.swing.JTextField qualificationBox;
    private javax.swing.JButton seAddBtn;
    private javax.swing.JButton seDeleteBtn;
    private javax.swing.JTextField seSid;
    private javax.swing.JTextField seSubId;
    private javax.swing.JCheckBox sem1sub1;
    private javax.swing.JCheckBox sem1sub2;
    private javax.swing.JCheckBox sem1sub3;
    private javax.swing.JCheckBox sem1sub4;
    private javax.swing.JCheckBox sem1sub5;
    private javax.swing.JLabel sem1subLabel;
    private javax.swing.JLabel sem1subLabel1;
    private javax.swing.JTextArea sem1subjects;
    private javax.swing.JCheckBox sem2sub1;
    private javax.swing.JCheckBox sem2sub2;
    private javax.swing.JCheckBox sem2sub3;
    private javax.swing.JCheckBox sem2sub4;
    private javax.swing.JCheckBox sem2sub5;
    private javax.swing.JTextArea sem2subjects;
    private javax.swing.JButton sepAddBtn;
    private javax.swing.JButton sepDeleteBtn;
    private javax.swing.JTextField sepSid;
    private javax.swing.JTextField sepSubId;
    private javax.swing.JRadioButton singleRadioButton;
    private javax.swing.JRadioButton singleRadioButton1;
    private javax.swing.JLabel subject1Label;
    private javax.swing.JLabel subject1Label1;
    private javax.swing.JButton subjectEnrollmentBtn;
    private javax.swing.JTable useTable;
    private javax.swing.JTextField yearCompletedBox;
    // End of variables declaration//GEN-END:variables
}
